//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';
import * as shared_ttypes from './shared_types.js';


import * as ttypes from './cmsisagent_types.js';
//HELPER FUNCTIONS AND STRUCTURES

const CMSISEventListener_onRteEvent_args = class {
  constructor(args) {
    this.event = null;
    if (args) {
      if (args.event !== undefined && args.event !== null) {
        this.event = new ttypes.RteEvent(args.event);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.event = new ttypes.RteEvent();
            this.event["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CMSISEventListener_onRteEvent_args');
      if (this.event !== null && this.event !== undefined) {
        output.writeFieldBegin('event', Thrift.Type.STRUCT, 1);
        this.event["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CMSISEventListener_onRteEvent_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CMSISEventListener_onRteEvent_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CMSISEventListenerClient = class CMSISEventListenerClient {
  constructor(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
  }
  seqid () { return this._seqid; }
  new_seqid () { return this._seqid += 1; }

  onRteEvent (event) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_onRteEvent(event);
    });
  }

  send_onRteEvent (event) {
    const output = new this.pClass(this.output);
    const params = {
      event: event
    };
    const args = new CMSISEventListener_onRteEvent_args(params);
    try {
      output.writeMessageBegin('onRteEvent', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_onRteEvent (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CMSISEventListener_onRteEvent_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }
};
export { CMSISEventListenerClient as Client };
const CMSISEventListenerProcessor = class CMSISEventListenerProcessor {
  constructor(handler) {
    this._handler = handler;
  }
  process (input, output) {
    const r = input.readMessageBegin();
    if (this['process_' + r.fname]) {
      return this['process_' + r.fname].call(this, r.rseqid, input, output);
    } else {
      input.skip(Thrift.Type.STRUCT);
      input.readMessageEnd();
      const x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
      output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
      x["write"](output);
      output.writeMessageEnd();
      output.flush();
    }
  }
  process_onRteEvent (seqid, input, output) {
    const args = new CMSISEventListener_onRteEvent_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.onRteEvent.length === 1) {
      new Promise((resolve) => resolve(this._handler.onRteEvent.bind(this._handler)(
        args.event
      ))).then(result => {
        const result_obj = new CMSISEventListener_onRteEvent_result({success: result});
        output.writeMessageBegin("onRteEvent", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("onRteEvent", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.onRteEvent(args.event, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CMSISEventListener_onRteEvent_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("onRteEvent", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("onRteEvent", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
};
export { CMSISEventListenerProcessor as Processor };
