//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';
import * as shared_ttypes from './shared_types.js';


const HeartbeatService = require('./HeartbeatService.js');
const HeartbeatServiceClient = HeartbeatService.Client;
const HeartbeatServiceProcessor = HeartbeatService.Processor;
import * as ttypes from './cspy_types.js';
//HELPER FUNCTIONS AND STRUCTURES

const ContextManager_setInspectionContext_args = class {
  constructor(args) {
    this.context = null;
    if (args) {
      if (args.context !== undefined && args.context !== null) {
        this.context = new shared_ttypes.ContextRef(args.context);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.context = new shared_ttypes.ContextRef();
            this.context["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_setInspectionContext_args');
      if (this.context !== null && this.context !== undefined) {
        output.writeFieldBegin('context', Thrift.Type.STRUCT, 1);
        this.context["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_setInspectionContext_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_setInspectionContext_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_findContext_args = class {
  constructor(args) {
    this.context = null;
    if (args) {
      if (args.context !== undefined && args.context !== null) {
        this.context = new shared_ttypes.ContextRef(args.context);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.context = new shared_ttypes.ContextRef();
            this.context["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_findContext_args');
      if (this.context !== null && this.context !== undefined) {
        output.writeFieldBegin('context', Thrift.Type.STRUCT, 1);
        this.context["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_findContext_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = new shared_ttypes.ContextRef(args.success);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new shared_ttypes.ContextRef();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_findContext_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getStack_args = class {
  constructor(args) {
    this.context = null;
    this.low = null;
    this.high = null;
    if (args) {
      if (args.context !== undefined && args.context !== null) {
        this.context = new shared_ttypes.ContextRef(args.context);
      }
      if (args.low !== undefined && args.low !== null) {
        this.low = args.low;
      }
      if (args.high !== undefined && args.high !== null) {
        this.high = args.high;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.context = new shared_ttypes.ContextRef();
            this.context["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.I32) {
            this.low = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.I32) {
            this.high = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getStack_args');
      if (this.context !== null && this.context !== undefined) {
        output.writeFieldBegin('context', Thrift.Type.STRUCT, 1);
        this.context["write"](output);
        output.writeFieldEnd();
      }
      if (this.low !== null && this.low !== undefined) {
        output.writeFieldBegin('low', Thrift.Type.I32, 2);
        output.writeI32(this.low);
        output.writeFieldEnd();
      }
      if (this.high !== null && this.high !== undefined) {
        output.writeFieldBegin('high', Thrift.Type.I32, 3);
        output.writeI32(this.high);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getStack_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyList(args.success, [shared_ttypes.ContextInfo]);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.LIST) {
            this.success = [];
            const _rtmp3116 = input.readListBegin();
            const _size115 = _rtmp3116.size || 0;
            for (let _i117 = 0; _i117 < _size115; ++_i117) {
              let elem118 = null;
              elem118 = new shared_ttypes.ContextInfo();
              elem118["read"](input);
              this.success.push(elem118);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getStack_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.LIST, 0);
        output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
        for (let iter119 in this.success) {
          if (this.success.hasOwnProperty(iter119)) {
            iter119 = this.success[iter119];
            iter119["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getStackDepth_args = class {
  constructor(args) {
    this.context = null;
    this.maxDepth = null;
    if (args) {
      if (args.context !== undefined && args.context !== null) {
        this.context = new shared_ttypes.ContextRef(args.context);
      }
      if (args.maxDepth !== undefined && args.maxDepth !== null) {
        this.maxDepth = args.maxDepth;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.context = new shared_ttypes.ContextRef();
            this.context["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.I32) {
            this.maxDepth = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getStackDepth_args');
      if (this.context !== null && this.context !== undefined) {
        output.writeFieldBegin('context', Thrift.Type.STRUCT, 1);
        this.context["write"](output);
        output.writeFieldEnd();
      }
      if (this.maxDepth !== null && this.maxDepth !== undefined) {
        output.writeFieldBegin('maxDepth', Thrift.Type.I32, 2);
        output.writeI32(this.maxDepth);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getStackDepth_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.I32) {
            this.success = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getStackDepth_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.I32, 0);
        output.writeI32(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getContextInfo_args = class {
  constructor(args) {
    this.context = null;
    if (args) {
      if (args.context !== undefined && args.context !== null) {
        this.context = new shared_ttypes.ContextRef(args.context);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.context = new shared_ttypes.ContextRef();
            this.context["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getContextInfo_args');
      if (this.context !== null && this.context !== undefined) {
        output.writeFieldBegin('context', Thrift.Type.STRUCT, 1);
        this.context["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getContextInfo_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = new shared_ttypes.ContextInfo(args.success);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new shared_ttypes.ContextInfo();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getContextInfo_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_compareContexts_args = class {
  constructor(args) {
    this.ctx1 = null;
    this.ctx2 = null;
    if (args) {
      if (args.ctx1 !== undefined && args.ctx1 !== null) {
        this.ctx1 = new shared_ttypes.ContextRef(args.ctx1);
      }
      if (args.ctx2 !== undefined && args.ctx2 !== null) {
        this.ctx2 = new shared_ttypes.ContextRef(args.ctx2);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.ctx1 = new shared_ttypes.ContextRef();
            this.ctx1["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.ctx2 = new shared_ttypes.ContextRef();
            this.ctx2["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_compareContexts_args');
      if (this.ctx1 !== null && this.ctx1 !== undefined) {
        output.writeFieldBegin('ctx1', Thrift.Type.STRUCT, 1);
        this.ctx1["write"](output);
        output.writeFieldEnd();
      }
      if (this.ctx2 !== null && this.ctx2 !== undefined) {
        output.writeFieldBegin('ctx2', Thrift.Type.STRUCT, 2);
        this.ctx2["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_compareContexts_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.BOOL) {
            this.success = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_compareContexts_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
        output.writeBool(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getLocals_args = class {
  constructor(args) {
    this.ctx = null;
    if (args) {
      if (args.ctx !== undefined && args.ctx !== null) {
        this.ctx = new shared_ttypes.ContextRef(args.ctx);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.ctx = new shared_ttypes.ContextRef();
            this.ctx["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getLocals_args');
      if (this.ctx !== null && this.ctx !== undefined) {
        output.writeFieldBegin('ctx', Thrift.Type.STRUCT, 1);
        this.ctx["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getLocals_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyList(args.success, [shared_ttypes.Symbol]);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.LIST) {
            this.success = [];
            const _rtmp3121 = input.readListBegin();
            const _size120 = _rtmp3121.size || 0;
            for (let _i122 = 0; _i122 < _size120; ++_i122) {
              let elem123 = null;
              elem123 = new shared_ttypes.Symbol();
              elem123["read"](input);
              this.success.push(elem123);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getLocals_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.LIST, 0);
        output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
        for (let iter124 in this.success) {
          if (this.success.hasOwnProperty(iter124)) {
            iter124 = this.success[iter124];
            iter124["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getParameters_args = class {
  constructor(args) {
    this.ctx = null;
    if (args) {
      if (args.ctx !== undefined && args.ctx !== null) {
        this.ctx = new shared_ttypes.ContextRef(args.ctx);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.ctx = new shared_ttypes.ContextRef();
            this.ctx["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getParameters_args');
      if (this.ctx !== null && this.ctx !== undefined) {
        output.writeFieldBegin('ctx', Thrift.Type.STRUCT, 1);
        this.ctx["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_getParameters_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyList(args.success, [shared_ttypes.Symbol]);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.LIST) {
            this.success = [];
            const _rtmp3126 = input.readListBegin();
            const _size125 = _rtmp3126.size || 0;
            for (let _i127 = 0; _i127 < _size125; ++_i127) {
              let elem128 = null;
              elem128 = new shared_ttypes.Symbol();
              elem128["read"](input);
              this.success.push(elem128);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_getParameters_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.LIST, 0);
        output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
        for (let iter129 in this.success) {
          if (this.success.hasOwnProperty(iter129)) {
            iter129 = this.success[iter129];
            iter129["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_isExecuting_args = class {
  constructor(args) {
    this.ctx = null;
    if (args) {
      if (args.ctx !== undefined && args.ctx !== null) {
        this.ctx = new shared_ttypes.ContextRef(args.ctx);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.ctx = new shared_ttypes.ContextRef();
            this.ctx["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_isExecuting_args');
      if (this.ctx !== null && this.ctx !== undefined) {
        output.writeFieldBegin('ctx', Thrift.Type.STRUCT, 1);
        this.ctx["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_isExecuting_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.BOOL) {
            this.success = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_isExecuting_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
        output.writeBool(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_setExecLocation_args = class {
  constructor(args) {
    this.ctx = null;
    this.ule = null;
    if (args) {
      if (args.ctx !== undefined && args.ctx !== null) {
        this.ctx = new shared_ttypes.ContextRef(args.ctx);
      }
      if (args.ule !== undefined && args.ule !== null) {
        this.ule = args.ule;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.ctx = new shared_ttypes.ContextRef();
            this.ctx["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRING) {
            this.ule = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_setExecLocation_args');
      if (this.ctx !== null && this.ctx !== undefined) {
        output.writeFieldBegin('ctx', Thrift.Type.STRUCT, 1);
        this.ctx["write"](output);
        output.writeFieldEnd();
      }
      if (this.ule !== null && this.ule !== undefined) {
        output.writeFieldBegin('ule', Thrift.Type.STRING, 2);
        output.writeString(this.ule);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManager_setExecLocation_result = class {
  constructor(args) {
    this.e = null;
    if (args instanceof shared_ttypes.CSpyException) {
        this.e = args;
        return;
    }
    if (args) {
      if (args.e !== undefined && args.e !== null) {
        this.e = args.e;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.e = new shared_ttypes.CSpyException();
            this.e["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('ContextManager_setExecLocation_result');
      if (this.e !== null && this.e !== undefined) {
        output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
        this.e["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const ContextManagerClient = class ContextManagerClient extends HeartbeatServiceClient {
  constructor(output, pClass) {
    super(output, pClass);
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
  }
  seqid () { return this._seqid; }
  new_seqid () { return this._seqid += 1; }

  setInspectionContext (context) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_setInspectionContext(context);
    });
  }

  send_setInspectionContext (context) {
    const output = new this.pClass(this.output);
    const params = {
      context: context
    };
    const args = new ContextManager_setInspectionContext_args(params);
    try {
      output.writeMessageBegin('setInspectionContext', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_setInspectionContext (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_setInspectionContext_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  findContext (context) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_findContext(context);
    });
  }

  send_findContext (context) {
    const output = new this.pClass(this.output);
    const params = {
      context: context
    };
    const args = new ContextManager_findContext_args(params);
    try {
      output.writeMessageBegin('findContext', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_findContext (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_findContext_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('findContext failed: unknown result');
  }

  getStack (context, low, high) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_getStack(context, low, high);
    });
  }

  send_getStack (context, low, high) {
    const output = new this.pClass(this.output);
    const params = {
      context: context,
      low: low,
      high: high
    };
    const args = new ContextManager_getStack_args(params);
    try {
      output.writeMessageBegin('getStack', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_getStack (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_getStack_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('getStack failed: unknown result');
  }

  getStackDepth (context, maxDepth) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_getStackDepth(context, maxDepth);
    });
  }

  send_getStackDepth (context, maxDepth) {
    const output = new this.pClass(this.output);
    const params = {
      context: context,
      maxDepth: maxDepth
    };
    const args = new ContextManager_getStackDepth_args(params);
    try {
      output.writeMessageBegin('getStackDepth', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_getStackDepth (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_getStackDepth_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('getStackDepth failed: unknown result');
  }

  getContextInfo (context) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_getContextInfo(context);
    });
  }

  send_getContextInfo (context) {
    const output = new this.pClass(this.output);
    const params = {
      context: context
    };
    const args = new ContextManager_getContextInfo_args(params);
    try {
      output.writeMessageBegin('getContextInfo', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_getContextInfo (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_getContextInfo_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('getContextInfo failed: unknown result');
  }

  compareContexts (ctx1, ctx2) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_compareContexts(ctx1, ctx2);
    });
  }

  send_compareContexts (ctx1, ctx2) {
    const output = new this.pClass(this.output);
    const params = {
      ctx1: ctx1,
      ctx2: ctx2
    };
    const args = new ContextManager_compareContexts_args(params);
    try {
      output.writeMessageBegin('compareContexts', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_compareContexts (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_compareContexts_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('compareContexts failed: unknown result');
  }

  getLocals (ctx) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_getLocals(ctx);
    });
  }

  send_getLocals (ctx) {
    const output = new this.pClass(this.output);
    const params = {
      ctx: ctx
    };
    const args = new ContextManager_getLocals_args(params);
    try {
      output.writeMessageBegin('getLocals', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_getLocals (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_getLocals_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('getLocals failed: unknown result');
  }

  getParameters (ctx) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_getParameters(ctx);
    });
  }

  send_getParameters (ctx) {
    const output = new this.pClass(this.output);
    const params = {
      ctx: ctx
    };
    const args = new ContextManager_getParameters_args(params);
    try {
      output.writeMessageBegin('getParameters', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_getParameters (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_getParameters_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('getParameters failed: unknown result');
  }

  isExecuting (ctx) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_isExecuting(ctx);
    });
  }

  send_isExecuting (ctx) {
    const output = new this.pClass(this.output);
    const params = {
      ctx: ctx
    };
    const args = new ContextManager_isExecuting_args(params);
    try {
      output.writeMessageBegin('isExecuting', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_isExecuting (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_isExecuting_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('isExecuting failed: unknown result');
  }

  setExecLocation (ctx, ule) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_setExecLocation(ctx, ule);
    });
  }

  send_setExecLocation (ctx, ule) {
    const output = new this.pClass(this.output);
    const params = {
      ctx: ctx,
      ule: ule
    };
    const args = new ContextManager_setExecLocation_args(params);
    try {
      output.writeMessageBegin('setExecLocation', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_setExecLocation (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ContextManager_setExecLocation_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.e) {
      return callback(result.e);
    }
    callback(null);
  }
};
export { ContextManagerClient as Client };
const ContextManagerProcessor = class ContextManagerProcessor extends HeartbeatServiceProcessor {
  constructor(handler) {
    super(handler);
    this._handler = handler;
  }
  process (input, output) {
    const r = input.readMessageBegin();
    if (this['process_' + r.fname]) {
      return this['process_' + r.fname].call(this, r.rseqid, input, output);
    } else {
      input.skip(Thrift.Type.STRUCT);
      input.readMessageEnd();
      const x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
      output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
      x["write"](output);
      output.writeMessageEnd();
      output.flush();
    }
  }
  process_setInspectionContext (seqid, input, output) {
    const args = new ContextManager_setInspectionContext_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.setInspectionContext.length === 1) {
      new Promise((resolve) => resolve(this._handler.setInspectionContext.bind(this._handler)(
        args.context
      ))).then(result => {
        const result_obj = new ContextManager_setInspectionContext_result({success: result});
        output.writeMessageBegin("setInspectionContext", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("setInspectionContext", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.setInspectionContext(args.context, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_setInspectionContext_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("setInspectionContext", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("setInspectionContext", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_findContext (seqid, input, output) {
    const args = new ContextManager_findContext_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.findContext.length === 1) {
      new Promise((resolve) => resolve(this._handler.findContext.bind(this._handler)(
        args.context
      ))).then(result => {
        const result_obj = new ContextManager_findContext_result({success: result});
        output.writeMessageBegin("findContext", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("findContext", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.findContext(args.context, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_findContext_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("findContext", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("findContext", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_getStack (seqid, input, output) {
    const args = new ContextManager_getStack_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.getStack.length === 3) {
      new Promise((resolve) => resolve(this._handler.getStack.bind(this._handler)(
        args.context,
        args.low,
        args.high
      ))).then(result => {
        const result_obj = new ContextManager_getStack_result({success: result});
        output.writeMessageBegin("getStack", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getStack", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.getStack(args.context, args.low, args.high, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_getStack_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("getStack", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("getStack", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_getStackDepth (seqid, input, output) {
    const args = new ContextManager_getStackDepth_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.getStackDepth.length === 2) {
      new Promise((resolve) => resolve(this._handler.getStackDepth.bind(this._handler)(
        args.context,
        args.maxDepth
      ))).then(result => {
        const result_obj = new ContextManager_getStackDepth_result({success: result});
        output.writeMessageBegin("getStackDepth", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getStackDepth", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.getStackDepth(args.context, args.maxDepth, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_getStackDepth_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("getStackDepth", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("getStackDepth", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_getContextInfo (seqid, input, output) {
    const args = new ContextManager_getContextInfo_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.getContextInfo.length === 1) {
      new Promise((resolve) => resolve(this._handler.getContextInfo.bind(this._handler)(
        args.context
      ))).then(result => {
        const result_obj = new ContextManager_getContextInfo_result({success: result});
        output.writeMessageBegin("getContextInfo", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getContextInfo", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.getContextInfo(args.context, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_getContextInfo_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("getContextInfo", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("getContextInfo", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_compareContexts (seqid, input, output) {
    const args = new ContextManager_compareContexts_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.compareContexts.length === 2) {
      new Promise((resolve) => resolve(this._handler.compareContexts.bind(this._handler)(
        args.ctx1,
        args.ctx2
      ))).then(result => {
        const result_obj = new ContextManager_compareContexts_result({success: result});
        output.writeMessageBegin("compareContexts", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("compareContexts", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.compareContexts(args.ctx1, args.ctx2, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_compareContexts_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("compareContexts", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("compareContexts", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_getLocals (seqid, input, output) {
    const args = new ContextManager_getLocals_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.getLocals.length === 1) {
      new Promise((resolve) => resolve(this._handler.getLocals.bind(this._handler)(
        args.ctx
      ))).then(result => {
        const result_obj = new ContextManager_getLocals_result({success: result});
        output.writeMessageBegin("getLocals", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getLocals", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.getLocals(args.ctx, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_getLocals_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("getLocals", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("getLocals", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_getParameters (seqid, input, output) {
    const args = new ContextManager_getParameters_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.getParameters.length === 1) {
      new Promise((resolve) => resolve(this._handler.getParameters.bind(this._handler)(
        args.ctx
      ))).then(result => {
        const result_obj = new ContextManager_getParameters_result({success: result});
        output.writeMessageBegin("getParameters", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getParameters", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.getParameters(args.ctx, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_getParameters_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("getParameters", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("getParameters", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_isExecuting (seqid, input, output) {
    const args = new ContextManager_isExecuting_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.isExecuting.length === 1) {
      new Promise((resolve) => resolve(this._handler.isExecuting.bind(this._handler)(
        args.ctx
      ))).then(result => {
        const result_obj = new ContextManager_isExecuting_result({success: result});
        output.writeMessageBegin("isExecuting", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("isExecuting", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.isExecuting(args.ctx, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ContextManager_isExecuting_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("isExecuting", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("isExecuting", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_setExecLocation (seqid, input, output) {
    const args = new ContextManager_setExecLocation_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.setExecLocation.length === 2) {
      new Promise((resolve) => resolve(this._handler.setExecLocation.bind(this._handler)(
        args.ctx,
        args.ule
      ))).then(result => {
        const result_obj = new ContextManager_setExecLocation_result({success: result});
        output.writeMessageBegin("setExecLocation", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof shared_ttypes.CSpyException) {
          result = new ContextManager_setExecLocation_result(err);
          output.writeMessageBegin("setExecLocation", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("setExecLocation", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.setExecLocation(args.ctx, args.ule, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.CSpyException) {
          result_obj = new ContextManager_setExecLocation_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("setExecLocation", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("setExecLocation", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
};
export { ContextManagerProcessor as Processor };
