//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';

import * as ttypes from './ServiceRegistry_types.js';
//HELPER FUNCTIONS AND STRUCTURES

const CSpyServiceRegistry_waitForService_args = class {
  constructor(args) {
    this.serviceName = null;
    this.timeout = null;
    if (args) {
      if (args.serviceName !== undefined && args.serviceName !== null) {
        this.serviceName = args.serviceName;
      }
      if (args.timeout !== undefined && args.timeout !== null) {
        this.timeout = args.timeout;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.serviceName = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.I32) {
            this.timeout = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_waitForService_args');
      if (this.serviceName !== null && this.serviceName !== undefined) {
        output.writeFieldBegin('serviceName', Thrift.Type.STRING, 1);
        output.writeString(this.serviceName);
        output.writeFieldEnd();
      }
      if (this.timeout !== null && this.timeout !== undefined) {
        output.writeFieldBegin('timeout', Thrift.Type.I32, 2);
        output.writeI32(this.timeout);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_waitForService_result = class {
  constructor(args) {
    this.success = null;
    this.e = null;
    if (args instanceof ttypes.ServiceException) {
        this.e = args;
        return;
    }
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = new ttypes.ServiceLocation(args.success);
      }
      if (args.e !== undefined && args.e !== null) {
        this.e = args.e;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new ttypes.ServiceLocation();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.e = new ttypes.ServiceException();
            this.e["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_waitForService_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      if (this.e !== null && this.e !== undefined) {
        output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
        this.e["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_registerService_args = class {
  constructor(args) {
    this.serviceName = null;
    this.location = null;
    if (args) {
      if (args.serviceName !== undefined && args.serviceName !== null) {
        this.serviceName = args.serviceName;
      }
      if (args.location !== undefined && args.location !== null) {
        this.location = new ttypes.ServiceLocation(args.location);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.serviceName = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.location = new ttypes.ServiceLocation();
            this.location["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_registerService_args');
      if (this.serviceName !== null && this.serviceName !== undefined) {
        output.writeFieldBegin('serviceName', Thrift.Type.STRING, 1);
        output.writeString(this.serviceName);
        output.writeFieldEnd();
      }
      if (this.location !== null && this.location !== undefined) {
        output.writeFieldBegin('location', Thrift.Type.STRUCT, 2);
        this.location["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_registerService_result = class {
  constructor(args) {
    this.e = null;
    if (args instanceof ttypes.ServiceException) {
        this.e = args;
        return;
    }
    if (args) {
      if (args.e !== undefined && args.e !== null) {
        this.e = args.e;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.e = new ttypes.ServiceException();
            this.e["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_registerService_result');
      if (this.e !== null && this.e !== undefined) {
        output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
        this.e["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_deregisterService_args = class {
  constructor(args) {
    this.serviceName = null;
    if (args) {
      if (args.serviceName !== undefined && args.serviceName !== null) {
        this.serviceName = args.serviceName;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.serviceName = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_deregisterService_args');
      if (this.serviceName !== null && this.serviceName !== undefined) {
        output.writeFieldBegin('serviceName', Thrift.Type.STRING, 1);
        output.writeString(this.serviceName);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_deregisterService_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_deregisterService_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_addServiceListener_args = class {
  constructor(args) {
    this.filterRegex = null;
    this.serviceListenerId = null;
    if (args) {
      if (args.filterRegex !== undefined && args.filterRegex !== null) {
        this.filterRegex = args.filterRegex;
      }
      if (args.serviceListenerId !== undefined && args.serviceListenerId !== null) {
        this.serviceListenerId = args.serviceListenerId;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.filterRegex = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRING) {
            this.serviceListenerId = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_addServiceListener_args');
      if (this.filterRegex !== null && this.filterRegex !== undefined) {
        output.writeFieldBegin('filterRegex', Thrift.Type.STRING, 1);
        output.writeString(this.filterRegex);
        output.writeFieldEnd();
      }
      if (this.serviceListenerId !== null && this.serviceListenerId !== undefined) {
        output.writeFieldBegin('serviceListenerId', Thrift.Type.STRING, 2);
        output.writeString(this.serviceListenerId);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_addServiceListener_result = class {
  constructor(args) {
    this.e = null;
    if (args instanceof ttypes.ServiceException) {
        this.e = args;
        return;
    }
    if (args) {
      if (args.e !== undefined && args.e !== null) {
        this.e = args.e;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.e = new ttypes.ServiceException();
            this.e["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_addServiceListener_result');
      if (this.e !== null && this.e !== undefined) {
        output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
        this.e["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_removeServiceListener_args = class {
  constructor(args) {
    this.serviceListenerId = null;
    if (args) {
      if (args.serviceListenerId !== undefined && args.serviceListenerId !== null) {
        this.serviceListenerId = args.serviceListenerId;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 2:
          if (ftype == Thrift.Type.STRING) {
            this.serviceListenerId = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_removeServiceListener_args');
      if (this.serviceListenerId !== null && this.serviceListenerId !== undefined) {
        output.writeFieldBegin('serviceListenerId', Thrift.Type.STRING, 2);
        output.writeString(this.serviceListenerId);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_removeServiceListener_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_removeServiceListener_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_getServices_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_getServices_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_getServices_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyMap(args.success, [ttypes.ServiceLocation]);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.MAP) {
            this.success = {};
            const _rtmp38 = input.readMapBegin();
            const _size7 = _rtmp38.size || 0;
            for (let _i9 = 0; _i9 < _size7; ++_i9) {
              let key10 = null;
              let val11 = null;
              key10 = input.readString();
              val11 = new ttypes.ServiceLocation();
              val11["read"](input);
              this.success[key10] = val11;
            }
            input.readMapEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_getServices_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.MAP, 0);
        output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRUCT, Thrift.objectLength(this.success));
        for (let kiter12 in this.success) {
          if (this.success.hasOwnProperty(kiter12)) {
            let viter13 = this.success[kiter12];
            output.writeString(kiter12);
            viter13["write"](output);
          }
        }
        output.writeMapEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_isAlive_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_isAlive_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_isAlive_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_isAlive_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_getSupportedTransports_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_getSupportedTransports_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_getSupportedTransports_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyList(args.success, [null]);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.LIST) {
            this.success = [];
            const _rtmp315 = input.readListBegin();
            const _size14 = _rtmp315.size || 0;
            for (let _i16 = 0; _i16 < _size14; ++_i16) {
              let elem17 = null;
              elem17 = input.readI32();
              this.success.push(elem17);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_getSupportedTransports_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.LIST, 0);
        output.writeListBegin(Thrift.Type.I32, this.success.length);
        for (let iter18 in this.success) {
          if (this.success.hasOwnProperty(iter18)) {
            iter18 = this.success[iter18];
            output.writeI32(iter18);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_createNamespace_args = class {
  constructor(args) {
    this.name = null;
    if (args) {
      if (args.name !== undefined && args.name !== null) {
        this.name = args.name;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.name = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_createNamespace_args');
      if (this.name !== null && this.name !== undefined) {
        output.writeFieldBegin('name', Thrift.Type.STRING, 1);
        output.writeString(this.name);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_createNamespace_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = new ttypes.ServiceLocation(args.success);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new ttypes.ServiceLocation();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_createNamespace_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_removeNamespace_args = class {
  constructor(args) {
    this.name = null;
    if (args) {
      if (args.name !== undefined && args.name !== null) {
        this.name = args.name;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.name = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_removeNamespace_args');
      if (this.name !== null && this.name !== undefined) {
        output.writeFieldBegin('name', Thrift.Type.STRING, 1);
        output.writeString(this.name);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_removeNamespace_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_removeNamespace_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_getNamespaces_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_getNamespaces_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistry_getNamespaces_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyList(args.success, [null]);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.LIST) {
            this.success = [];
            const _rtmp320 = input.readListBegin();
            const _size19 = _rtmp320.size || 0;
            for (let _i21 = 0; _i21 < _size19; ++_i21) {
              let elem22 = null;
              elem22 = input.readString();
              this.success.push(elem22);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyServiceRegistry_getNamespaces_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.LIST, 0);
        output.writeListBegin(Thrift.Type.STRING, this.success.length);
        for (let iter23 in this.success) {
          if (this.success.hasOwnProperty(iter23)) {
            iter23 = this.success[iter23];
            output.writeString(iter23);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const CSpyServiceRegistryClient = class CSpyServiceRegistryClient {
  constructor(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
  }
  seqid () { return this._seqid; }
  new_seqid () { return this._seqid += 1; }

  waitForService (serviceName, timeout) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_waitForService(serviceName, timeout);
    });
  }

  send_waitForService (serviceName, timeout) {
    const output = new this.pClass(this.output);
    const params = {
      serviceName: serviceName,
      timeout: timeout
    };
    const args = new CSpyServiceRegistry_waitForService_args(params);
    try {
      output.writeMessageBegin('waitForService', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_waitForService (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_waitForService_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.e) {
      return callback(result.e);
    }
    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('waitForService failed: unknown result');
  }

  registerService (serviceName, location) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_registerService(serviceName, location);
    });
  }

  send_registerService (serviceName, location) {
    const output = new this.pClass(this.output);
    const params = {
      serviceName: serviceName,
      location: location
    };
    const args = new CSpyServiceRegistry_registerService_args(params);
    try {
      output.writeMessageBegin('registerService', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_registerService (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_registerService_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.e) {
      return callback(result.e);
    }
    callback(null);
  }

  deregisterService (serviceName) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_deregisterService(serviceName);
    });
  }

  send_deregisterService (serviceName) {
    const output = new this.pClass(this.output);
    const params = {
      serviceName: serviceName
    };
    const args = new CSpyServiceRegistry_deregisterService_args(params);
    try {
      output.writeMessageBegin('deregisterService', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_deregisterService (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_deregisterService_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  addServiceListener (filterRegex, serviceListenerId) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_addServiceListener(filterRegex, serviceListenerId);
    });
  }

  send_addServiceListener (filterRegex, serviceListenerId) {
    const output = new this.pClass(this.output);
    const params = {
      filterRegex: filterRegex,
      serviceListenerId: serviceListenerId
    };
    const args = new CSpyServiceRegistry_addServiceListener_args(params);
    try {
      output.writeMessageBegin('addServiceListener', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_addServiceListener (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_addServiceListener_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.e) {
      return callback(result.e);
    }
    callback(null);
  }

  removeServiceListener (serviceListenerId) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_removeServiceListener(serviceListenerId);
    });
  }

  send_removeServiceListener (serviceListenerId) {
    const output = new this.pClass(this.output);
    const params = {
      serviceListenerId: serviceListenerId
    };
    const args = new CSpyServiceRegistry_removeServiceListener_args(params);
    try {
      output.writeMessageBegin('removeServiceListener', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_removeServiceListener (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_removeServiceListener_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  getServices () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_getServices();
    });
  }

  send_getServices () {
    const output = new this.pClass(this.output);
    const args = new CSpyServiceRegistry_getServices_args();
    try {
      output.writeMessageBegin('getServices', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_getServices (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_getServices_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('getServices failed: unknown result');
  }

  isAlive () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_isAlive();
    });
  }

  send_isAlive () {
    const output = new this.pClass(this.output);
    const args = new CSpyServiceRegistry_isAlive_args();
    try {
      output.writeMessageBegin('isAlive', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_isAlive (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_isAlive_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  getSupportedTransports () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_getSupportedTransports();
    });
  }

  send_getSupportedTransports () {
    const output = new this.pClass(this.output);
    const args = new CSpyServiceRegistry_getSupportedTransports_args();
    try {
      output.writeMessageBegin('getSupportedTransports', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_getSupportedTransports (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_getSupportedTransports_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('getSupportedTransports failed: unknown result');
  }

  createNamespace (name) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_createNamespace(name);
    });
  }

  send_createNamespace (name) {
    const output = new this.pClass(this.output);
    const params = {
      name: name
    };
    const args = new CSpyServiceRegistry_createNamespace_args(params);
    try {
      output.writeMessageBegin('createNamespace', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_createNamespace (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_createNamespace_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('createNamespace failed: unknown result');
  }

  removeNamespace (name) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_removeNamespace(name);
    });
  }

  send_removeNamespace (name) {
    const output = new this.pClass(this.output);
    const params = {
      name: name
    };
    const args = new CSpyServiceRegistry_removeNamespace_args(params);
    try {
      output.writeMessageBegin('removeNamespace', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_removeNamespace (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_removeNamespace_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  getNamespaces () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_getNamespaces();
    });
  }

  send_getNamespaces () {
    const output = new this.pClass(this.output);
    const args = new CSpyServiceRegistry_getNamespaces_args();
    try {
      output.writeMessageBegin('getNamespaces', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_getNamespaces (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new CSpyServiceRegistry_getNamespaces_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('getNamespaces failed: unknown result');
  }
};
export { CSpyServiceRegistryClient as Client };
const CSpyServiceRegistryProcessor = class CSpyServiceRegistryProcessor {
  constructor(handler) {
    this._handler = handler;
  }
  process (input, output) {
    const r = input.readMessageBegin();
    if (this['process_' + r.fname]) {
      return this['process_' + r.fname].call(this, r.rseqid, input, output);
    } else {
      input.skip(Thrift.Type.STRUCT);
      input.readMessageEnd();
      const x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
      output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
      x["write"](output);
      output.writeMessageEnd();
      output.flush();
    }
  }
  process_waitForService (seqid, input, output) {
    const args = new CSpyServiceRegistry_waitForService_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.waitForService.length === 2) {
      new Promise((resolve) => resolve(this._handler.waitForService.bind(this._handler)(
        args.serviceName,
        args.timeout
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_waitForService_result({success: result});
        output.writeMessageBegin("waitForService", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof ttypes.ServiceException) {
          result = new CSpyServiceRegistry_waitForService_result(err);
          output.writeMessageBegin("waitForService", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("waitForService", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.waitForService(args.serviceName, args.timeout, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof ttypes.ServiceException) {
          result_obj = new CSpyServiceRegistry_waitForService_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("waitForService", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("waitForService", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_registerService (seqid, input, output) {
    const args = new CSpyServiceRegistry_registerService_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.registerService.length === 2) {
      new Promise((resolve) => resolve(this._handler.registerService.bind(this._handler)(
        args.serviceName,
        args.location
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_registerService_result({success: result});
        output.writeMessageBegin("registerService", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof ttypes.ServiceException) {
          result = new CSpyServiceRegistry_registerService_result(err);
          output.writeMessageBegin("registerService", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("registerService", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.registerService(args.serviceName, args.location, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof ttypes.ServiceException) {
          result_obj = new CSpyServiceRegistry_registerService_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("registerService", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("registerService", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_deregisterService (seqid, input, output) {
    const args = new CSpyServiceRegistry_deregisterService_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.deregisterService.length === 1) {
      new Promise((resolve) => resolve(this._handler.deregisterService.bind(this._handler)(
        args.serviceName
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_deregisterService_result({success: result});
        output.writeMessageBegin("deregisterService", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("deregisterService", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.deregisterService(args.serviceName, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CSpyServiceRegistry_deregisterService_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("deregisterService", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("deregisterService", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_addServiceListener (seqid, input, output) {
    const args = new CSpyServiceRegistry_addServiceListener_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.addServiceListener.length === 2) {
      new Promise((resolve) => resolve(this._handler.addServiceListener.bind(this._handler)(
        args.filterRegex,
        args.serviceListenerId
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_addServiceListener_result({success: result});
        output.writeMessageBegin("addServiceListener", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof ttypes.ServiceException) {
          result = new CSpyServiceRegistry_addServiceListener_result(err);
          output.writeMessageBegin("addServiceListener", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("addServiceListener", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.addServiceListener(args.filterRegex, args.serviceListenerId, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof ttypes.ServiceException) {
          result_obj = new CSpyServiceRegistry_addServiceListener_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("addServiceListener", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("addServiceListener", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_removeServiceListener (seqid, input, output) {
    const args = new CSpyServiceRegistry_removeServiceListener_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.removeServiceListener.length === 1) {
      new Promise((resolve) => resolve(this._handler.removeServiceListener.bind(this._handler)(
        args.serviceListenerId
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_removeServiceListener_result({success: result});
        output.writeMessageBegin("removeServiceListener", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("removeServiceListener", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.removeServiceListener(args.serviceListenerId, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CSpyServiceRegistry_removeServiceListener_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("removeServiceListener", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("removeServiceListener", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_getServices (seqid, input, output) {
    const args = new CSpyServiceRegistry_getServices_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.getServices.length === 0) {
      new Promise((resolve) => resolve(this._handler.getServices.bind(this._handler)(
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_getServices_result({success: result});
        output.writeMessageBegin("getServices", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getServices", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.getServices((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CSpyServiceRegistry_getServices_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("getServices", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("getServices", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_isAlive (seqid, input, output) {
    const args = new CSpyServiceRegistry_isAlive_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.isAlive.length === 0) {
      new Promise((resolve) => resolve(this._handler.isAlive.bind(this._handler)(
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_isAlive_result({success: result});
        output.writeMessageBegin("isAlive", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("isAlive", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.isAlive((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CSpyServiceRegistry_isAlive_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("isAlive", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("isAlive", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_getSupportedTransports (seqid, input, output) {
    const args = new CSpyServiceRegistry_getSupportedTransports_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.getSupportedTransports.length === 0) {
      new Promise((resolve) => resolve(this._handler.getSupportedTransports.bind(this._handler)(
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_getSupportedTransports_result({success: result});
        output.writeMessageBegin("getSupportedTransports", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getSupportedTransports", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.getSupportedTransports((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CSpyServiceRegistry_getSupportedTransports_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("getSupportedTransports", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("getSupportedTransports", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_createNamespace (seqid, input, output) {
    const args = new CSpyServiceRegistry_createNamespace_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.createNamespace.length === 1) {
      new Promise((resolve) => resolve(this._handler.createNamespace.bind(this._handler)(
        args.name
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_createNamespace_result({success: result});
        output.writeMessageBegin("createNamespace", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("createNamespace", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.createNamespace(args.name, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CSpyServiceRegistry_createNamespace_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("createNamespace", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("createNamespace", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_removeNamespace (seqid, input, output) {
    const args = new CSpyServiceRegistry_removeNamespace_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.removeNamespace.length === 1) {
      new Promise((resolve) => resolve(this._handler.removeNamespace.bind(this._handler)(
        args.name
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_removeNamespace_result({success: result});
        output.writeMessageBegin("removeNamespace", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("removeNamespace", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.removeNamespace(args.name, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CSpyServiceRegistry_removeNamespace_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("removeNamespace", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("removeNamespace", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_getNamespaces (seqid, input, output) {
    const args = new CSpyServiceRegistry_getNamespaces_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.getNamespaces.length === 0) {
      new Promise((resolve) => resolve(this._handler.getNamespaces.bind(this._handler)(
      ))).then(result => {
        const result_obj = new CSpyServiceRegistry_getNamespaces_result({success: result});
        output.writeMessageBegin("getNamespaces", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getNamespaces", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.getNamespaces((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new CSpyServiceRegistry_getNamespaces_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("getNamespaces", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("getNamespaces", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
};
export { CSpyServiceRegistryProcessor as Processor };
