//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Int64 = require('node-int64');
import { v4 as uuid } from 'uuid';
type uuid = string;
import shared_ttypes = require('./shared_types.js');


import ttypes = require('./memory_types');
import CSpyMemoryBlock = ttypes.CSpyMemoryBlock

declare class Client {
    private output: thrift.TTransport;
    private pClass: thrift.TProtocol;
    private _seqid: number;

    constructor(output: thrift.TTransport, pClass: { new(trans: thrift.TTransport): thrift.TProtocol });

    readMemory(location: shared_ttypes.Location, wordsize: number, bitsize: number, count: number): Promise<Buffer>;

    readMemory(location: shared_ttypes.Location, wordsize: number, bitsize: number, count: number, callback?: (error: shared_ttypes.CSpyException, response: Buffer)=>void): void;

    readMemoryBlock(location: shared_ttypes.Location, wordsize: number, bitsize: number, count: number): Promise<CSpyMemoryBlock>;

    readMemoryBlock(location: shared_ttypes.Location, wordsize: number, bitsize: number, count: number, callback?: (error: shared_ttypes.CSpyException, response: CSpyMemoryBlock)=>void): void;

    writeMemory(location: shared_ttypes.Location, wordsize: number, bitsize: number, count: number, buf: Buffer): Promise<void>;

    writeMemory(location: shared_ttypes.Location, wordsize: number, bitsize: number, count: number, buf: Buffer, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;
  }

declare class Processor {
  private _handler: object;

  constructor(handler: object);
  process(input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_readMemory(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_readMemoryBlock(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_writeMemory(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
}
