//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';
import * as shared_ttypes from './shared_types.js';


import * as HeartbeatService from './HeartbeatService.js';
const HeartbeatServiceClient = HeartbeatService.Client;
const HeartbeatServiceProcessor = HeartbeatService.Processor;
import * as ttypes from './disassembly_types.js';
//HELPER FUNCTIONS AND STRUCTURES

const Disassembly_disassembleRange_args = class {
  constructor(args) {
    this._from = null;
    this._to = null;
    this.context = null;
    if (args) {
      if (args._from !== undefined && args._from !== null) {
        this._from = new shared_ttypes.Location(args._from);
      }
      if (args._to !== undefined && args._to !== null) {
        this._to = new shared_ttypes.Location(args._to);
      }
      if (args.context !== undefined && args.context !== null) {
        this.context = new shared_ttypes.ContextRef(args.context);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this._from = new shared_ttypes.Location();
            this._from["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this._to = new shared_ttypes.Location();
            this._to["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.STRUCT) {
            this.context = new shared_ttypes.ContextRef();
            this.context["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Disassembly_disassembleRange_args');
      if (this._from !== null && this._from !== undefined) {
        output.writeFieldBegin('_from', Thrift.Type.STRUCT, 1);
        this._from["write"](output);
        output.writeFieldEnd();
      }
      if (this._to !== null && this._to !== undefined) {
        output.writeFieldBegin('_to', Thrift.Type.STRUCT, 2);
        this._to["write"](output);
        output.writeFieldEnd();
      }
      if (this.context !== null && this.context !== undefined) {
        output.writeFieldBegin('context', Thrift.Type.STRUCT, 3);
        this.context["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Disassembly_disassembleRange_result = class {
  constructor(args) {
    this.success = null;
    this.e = null;
    if (args instanceof shared_ttypes.CSpyException) {
        this.e = args;
        return;
    }
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyList(args.success, [ttypes.DisassembledLocation]);
      }
      if (args.e !== undefined && args.e !== null) {
        this.e = args.e;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.LIST) {
            this.success = [];
            const _rtmp36 = input.readListBegin();
            const _size5 = _rtmp36.size || 0;
            for (let _i7 = 0; _i7 < _size5; ++_i7) {
              let elem8 = null;
              elem8 = new ttypes.DisassembledLocation();
              elem8["read"](input);
              this.success.push(elem8);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.e = new shared_ttypes.CSpyException();
            this.e["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Disassembly_disassembleRange_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.LIST, 0);
        output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
        for (let iter9 in this.success) {
          if (this.success.hasOwnProperty(iter9)) {
            iter9 = this.success[iter9];
            iter9["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      if (this.e !== null && this.e !== undefined) {
        output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
        this.e["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Disassembly_disassembleLines_args = class {
  constructor(args) {
    this._from = null;
    this.numLines = null;
    this.context = null;
    if (args) {
      if (args._from !== undefined && args._from !== null) {
        this._from = new shared_ttypes.Location(args._from);
      }
      if (args.numLines !== undefined && args.numLines !== null) {
        this.numLines = args.numLines;
      }
      if (args.context !== undefined && args.context !== null) {
        this.context = new shared_ttypes.ContextRef(args.context);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this._from = new shared_ttypes.Location();
            this._from["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.I32) {
            this.numLines = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.STRUCT) {
            this.context = new shared_ttypes.ContextRef();
            this.context["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Disassembly_disassembleLines_args');
      if (this._from !== null && this._from !== undefined) {
        output.writeFieldBegin('_from', Thrift.Type.STRUCT, 1);
        this._from["write"](output);
        output.writeFieldEnd();
      }
      if (this.numLines !== null && this.numLines !== undefined) {
        output.writeFieldBegin('numLines', Thrift.Type.I32, 2);
        output.writeI32(this.numLines);
        output.writeFieldEnd();
      }
      if (this.context !== null && this.context !== undefined) {
        output.writeFieldBegin('context', Thrift.Type.STRUCT, 3);
        this.context["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Disassembly_disassembleLines_result = class {
  constructor(args) {
    this.success = null;
    this.e = null;
    if (args instanceof shared_ttypes.CSpyException) {
        this.e = args;
        return;
    }
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyList(args.success, [ttypes.DisassembledLocation]);
      }
      if (args.e !== undefined && args.e !== null) {
        this.e = args.e;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.LIST) {
            this.success = [];
            const _rtmp311 = input.readListBegin();
            const _size10 = _rtmp311.size || 0;
            for (let _i12 = 0; _i12 < _size10; ++_i12) {
              let elem13 = null;
              elem13 = new ttypes.DisassembledLocation();
              elem13["read"](input);
              this.success.push(elem13);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.e = new shared_ttypes.CSpyException();
            this.e["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Disassembly_disassembleLines_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.LIST, 0);
        output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
        for (let iter14 in this.success) {
          if (this.success.hasOwnProperty(iter14)) {
            iter14 = this.success[iter14];
            iter14["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      if (this.e !== null && this.e !== undefined) {
        output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
        this.e["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const DisassemblyClient = class DisassemblyClient extends HeartbeatServiceClient {
  constructor(output, pClass) {
    super(output, pClass);
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
  }
  seqid () { return this._seqid; }
  new_seqid () { return this._seqid += 1; }

  disassembleRange (_from, _to, context) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_disassembleRange(_from, _to, context);
    });
  }

  send_disassembleRange (_from, _to, context) {
    const output = new this.pClass(this.output);
    const params = {
      _from: _from,
      _to: _to,
      context: context
    };
    const args = new Disassembly_disassembleRange_args(params);
    try {
      output.writeMessageBegin('disassembleRange', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_disassembleRange (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Disassembly_disassembleRange_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.e) {
      return callback(result.e);
    }
    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('disassembleRange failed: unknown result');
  }

  disassembleLines (_from, numLines, context) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_disassembleLines(_from, numLines, context);
    });
  }

  send_disassembleLines (_from, numLines, context) {
    const output = new this.pClass(this.output);
    const params = {
      _from: _from,
      numLines: numLines,
      context: context
    };
    const args = new Disassembly_disassembleLines_args(params);
    try {
      output.writeMessageBegin('disassembleLines', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_disassembleLines (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Disassembly_disassembleLines_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.e) {
      return callback(result.e);
    }
    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('disassembleLines failed: unknown result');
  }
};
export { DisassemblyClient as Client };
const DisassemblyProcessor = class DisassemblyProcessor extends HeartbeatServiceProcessor {
  constructor(handler) {
    super(handler);
    this._handler = handler;
  }
  process (input, output) {
    const r = input.readMessageBegin();
    if (this['process_' + r.fname]) {
      return this['process_' + r.fname].call(this, r.rseqid, input, output);
    } else {
      input.skip(Thrift.Type.STRUCT);
      input.readMessageEnd();
      const x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
      output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
      x["write"](output);
      output.writeMessageEnd();
      output.flush();
    }
  }
  process_disassembleRange (seqid, input, output) {
    const args = new Disassembly_disassembleRange_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.disassembleRange.length === 3) {
      new Promise((resolve) => resolve(this._handler.disassembleRange.bind(this._handler)(
        args._from,
        args._to,
        args.context
      ))).then(result => {
        const result_obj = new Disassembly_disassembleRange_result({success: result});
        output.writeMessageBegin("disassembleRange", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof shared_ttypes.CSpyException) {
          result = new Disassembly_disassembleRange_result(err);
          output.writeMessageBegin("disassembleRange", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("disassembleRange", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.disassembleRange(args._from, args._to, args.context, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.CSpyException) {
          result_obj = new Disassembly_disassembleRange_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("disassembleRange", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("disassembleRange", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_disassembleLines (seqid, input, output) {
    const args = new Disassembly_disassembleLines_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.disassembleLines.length === 3) {
      new Promise((resolve) => resolve(this._handler.disassembleLines.bind(this._handler)(
        args._from,
        args.numLines,
        args.context
      ))).then(result => {
        const result_obj = new Disassembly_disassembleLines_result({success: result});
        output.writeMessageBegin("disassembleLines", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof shared_ttypes.CSpyException) {
          result = new Disassembly_disassembleLines_result(err);
          output.writeMessageBegin("disassembleLines", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("disassembleLines", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.disassembleLines(args._from, args.numLines, args.context, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.CSpyException) {
          result_obj = new Disassembly_disassembleLines_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("disassembleLines", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("disassembleLines", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
};
export { DisassemblyProcessor as Processor };
