/// <reference path="HeartbeatService.d.ts" />
//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Int64 = require('node-int64');
import { v4 as uuid } from 'uuid';
type uuid = string;
import shared_ttypes = require('./shared_types.js');


import ttypes = require('./disassembly_types');
import DISASSEMBLY_SERVICE = ttypes.DISASSEMBLY_SERVICE
import DisassembledLocation = ttypes.DisassembledLocation
import HeartbeatService = require('./HeartbeatService.js');

/**
 * The Disassembly service retrieves assembler instructions for a specific memory range
 */
declare class Client extends HeartbeatService.Client {
    constructor(output: thrift.TTransport, pClass: { new(trans: thrift.TTransport): thrift.TProtocol });

    /**
     * Retrieve a list of disassembled instructions for a specific memory range.
     */
    disassembleRange(_from: shared_ttypes.Location, _to: shared_ttypes.Location, context: shared_ttypes.ContextRef): Promise<DisassembledLocation[]>;

    /**
     * Retrieve a list of disassembled instructions for a specific memory range.
     */
    disassembleRange(_from: shared_ttypes.Location, _to: shared_ttypes.Location, context: shared_ttypes.ContextRef, callback?: (error: shared_ttypes.CSpyException, response: DisassembledLocation[])=>void): void;

    /**
     * This method is currently not implemented and will fail if called.
     */
    disassembleLines(_from: shared_ttypes.Location, numLines: number, context: shared_ttypes.ContextRef): Promise<DisassembledLocation[]>;

    /**
     * This method is currently not implemented and will fail if called.
     */
    disassembleLines(_from: shared_ttypes.Location, numLines: number, context: shared_ttypes.ContextRef, callback?: (error: shared_ttypes.CSpyException, response: DisassembledLocation[])=>void): void;
  }

declare class Processor extends HeartbeatService.Processor {
  constructor(handler: object);
  process(input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_disassembleRange(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_disassembleLines(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
}
