//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';
import * as shared_ttypes from './shared_types.js';
import * as cspy_ttypes from './cspy_types.js';
import * as ServiceRegistry_ttypes from './ServiceRegistry_types.js';


const HeartbeatService = require('./HeartbeatService.js');
const HeartbeatServiceClient = HeartbeatService.Client;
const HeartbeatServiceProcessor = HeartbeatService.Processor;
import * as ttypes from './ampsync_types.js';
//HELPER FUNCTIONS AND STRUCTURES

const Gatekeeper_SetRunAllCores_args = class {
  constructor(args) {
    this.all = null;
    if (args) {
      if (args.all !== undefined && args.all !== null) {
        this.all = args.all;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.BOOL) {
            this.all = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SetRunAllCores_args');
      if (this.all !== null && this.all !== undefined) {
        output.writeFieldBegin('all', Thrift.Type.BOOL, 1);
        output.writeBool(this.all);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SetRunAllCores_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SetRunAllCores_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SetStartOneStartsAll_args = class {
  constructor(args) {
    this.on = null;
    if (args) {
      if (args.on !== undefined && args.on !== null) {
        this.on = args.on;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.BOOL) {
            this.on = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SetStartOneStartsAll_args');
      if (this.on !== null && this.on !== undefined) {
        output.writeFieldBegin('on', Thrift.Type.BOOL, 1);
        output.writeBool(this.on);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SetStartOneStartsAll_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SetStartOneStartsAll_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SetSoftCTI_args = class {
  constructor(args) {
    this.on = null;
    if (args) {
      if (args.on !== undefined && args.on !== null) {
        this.on = args.on;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.BOOL) {
            this.on = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SetSoftCTI_args');
      if (this.on !== null && this.on !== undefined) {
        output.writeFieldBegin('on', Thrift.Type.BOOL, 1);
        output.writeBool(this.on);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SetSoftCTI_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SetSoftCTI_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_BeforeLowLevelGo_args = class {
  constructor(args) {
    this.core = null;
    this.multi = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
      if (args.multi !== undefined && args.multi !== null) {
        this.multi = args.multi;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.BOOL) {
            this.multi = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_BeforeLowLevelGo_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      if (this.multi !== null && this.multi !== undefined) {
        output.writeFieldBegin('multi', Thrift.Type.BOOL, 2);
        output.writeBool(this.multi);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_BeforeLowLevelGo_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.I32) {
            this.success = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_BeforeLowLevelGo_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.I32, 0);
        output.writeI32(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_StartedCPU_args = class {
  constructor(args) {
    this.core = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_StartedCPU_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_StartedCPU_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_StartedCPU_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_CPUStoped_args = class {
  constructor(args) {
    this.core = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_CPUStoped_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_CPUStoped_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_CPUStoped_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_IsTargetStopped_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_IsTargetStopped_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_IsTargetStopped_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.BOOL) {
            this.success = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_IsTargetStopped_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
        output.writeBool(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_AfterLowLevelGo_args = class {
  constructor(args) {
    this.core = null;
    this.code = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
      if (args.code !== undefined && args.code !== null) {
        this.code = args.code;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.I32) {
            this.code = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_AfterLowLevelGo_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      if (this.code !== null && this.code !== undefined) {
        output.writeFieldBegin('code', Thrift.Type.I32, 2);
        output.writeI32(this.code);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_AfterLowLevelGo_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.I32) {
            this.success = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_AfterLowLevelGo_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.I32, 0);
        output.writeI32(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_Reset_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_Reset_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_Reset_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_Reset_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_StopAll_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_StopAll_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_StopAll_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_StopAll_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SpontaneousCoreStatusChange_args = class {
  constructor(args) {
    this.core = null;
    this.status = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
      if (args.status !== undefined && args.status !== null) {
        this.status = args.status;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.I32) {
            this.status = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SpontaneousCoreStatusChange_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      if (this.status !== null && this.status !== undefined) {
        output.writeFieldBegin('status', Thrift.Type.I32, 2);
        output.writeI32(this.status);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SpontaneousCoreStatusChange_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SpontaneousCoreStatusChange_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_GetCoreStatus_args = class {
  constructor(args) {
    this.core = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_GetCoreStatus_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_GetCoreStatus_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.I32) {
            this.success = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_GetCoreStatus_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.I32, 0);
        output.writeI32(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_IsItOkToStopCore_args = class {
  constructor(args) {
    this.core = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_IsItOkToStopCore_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_IsItOkToStopCore_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.BOOL) {
            this.success = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_IsItOkToStopCore_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
        output.writeBool(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SetCPUStatusPolling_args = class {
  constructor(args) {
    this.on = null;
    if (args) {
      if (args.on !== undefined && args.on !== null) {
        this.on = args.on;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.BOOL) {
            this.on = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SetCPUStatusPolling_args');
      if (this.on !== null && this.on !== undefined) {
        output.writeFieldBegin('on', Thrift.Type.BOOL, 1);
        output.writeBool(this.on);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_SetCPUStatusPolling_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_SetCPUStatusPolling_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_AckCPUStatusPolling_args = class {
  constructor(args) {
    this.coreCount = null;
    if (args) {
      if (args.coreCount !== undefined && args.coreCount !== null) {
        this.coreCount = args.coreCount;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.coreCount = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_AckCPUStatusPolling_args');
      if (this.coreCount !== null && this.coreCount !== undefined) {
        output.writeFieldBegin('coreCount', Thrift.Type.I32, 1);
        output.writeI32(this.coreCount);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const Gatekeeper_AckCPUStatusPolling_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Gatekeeper_AckCPUStatusPolling_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const GatekeeperClient = class GatekeeperClient extends HeartbeatServiceClient {
  constructor(output, pClass) {
    super(output, pClass);
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
  }
  seqid () { return this._seqid; }
  new_seqid () { return this._seqid += 1; }

  SetRunAllCores (all) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_SetRunAllCores(all);
    });
  }

  send_SetRunAllCores (all) {
    const output = new this.pClass(this.output);
    const params = {
      all: all
    };
    const args = new Gatekeeper_SetRunAllCores_args(params);
    try {
      output.writeMessageBegin('SetRunAllCores', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_SetRunAllCores (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_SetRunAllCores_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  SetStartOneStartsAll (on) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_SetStartOneStartsAll(on);
    });
  }

  send_SetStartOneStartsAll (on) {
    const output = new this.pClass(this.output);
    const params = {
      on: on
    };
    const args = new Gatekeeper_SetStartOneStartsAll_args(params);
    try {
      output.writeMessageBegin('SetStartOneStartsAll', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_SetStartOneStartsAll (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_SetStartOneStartsAll_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  SetSoftCTI (on) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_SetSoftCTI(on);
    });
  }

  send_SetSoftCTI (on) {
    const output = new this.pClass(this.output);
    const params = {
      on: on
    };
    const args = new Gatekeeper_SetSoftCTI_args(params);
    try {
      output.writeMessageBegin('SetSoftCTI', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_SetSoftCTI (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_SetSoftCTI_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  BeforeLowLevelGo (core, multi) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_BeforeLowLevelGo(core, multi);
    });
  }

  send_BeforeLowLevelGo (core, multi) {
    const output = new this.pClass(this.output);
    const params = {
      core: core,
      multi: multi
    };
    const args = new Gatekeeper_BeforeLowLevelGo_args(params);
    try {
      output.writeMessageBegin('BeforeLowLevelGo', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_BeforeLowLevelGo (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_BeforeLowLevelGo_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('BeforeLowLevelGo failed: unknown result');
  }

  StartedCPU (core) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_StartedCPU(core);
    });
  }

  send_StartedCPU (core) {
    const output = new this.pClass(this.output);
    const params = {
      core: core
    };
    const args = new Gatekeeper_StartedCPU_args(params);
    try {
      output.writeMessageBegin('StartedCPU', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_StartedCPU (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_StartedCPU_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  CPUStoped (core) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_CPUStoped(core);
    });
  }

  send_CPUStoped (core) {
    const output = new this.pClass(this.output);
    const params = {
      core: core
    };
    const args = new Gatekeeper_CPUStoped_args(params);
    try {
      output.writeMessageBegin('CPUStoped', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_CPUStoped (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_CPUStoped_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  IsTargetStopped () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_IsTargetStopped();
    });
  }

  send_IsTargetStopped () {
    const output = new this.pClass(this.output);
    const args = new Gatekeeper_IsTargetStopped_args();
    try {
      output.writeMessageBegin('IsTargetStopped', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_IsTargetStopped (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_IsTargetStopped_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('IsTargetStopped failed: unknown result');
  }

  AfterLowLevelGo (core, code) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_AfterLowLevelGo(core, code);
    });
  }

  send_AfterLowLevelGo (core, code) {
    const output = new this.pClass(this.output);
    const params = {
      core: core,
      code: code
    };
    const args = new Gatekeeper_AfterLowLevelGo_args(params);
    try {
      output.writeMessageBegin('AfterLowLevelGo', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_AfterLowLevelGo (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_AfterLowLevelGo_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('AfterLowLevelGo failed: unknown result');
  }

  Reset () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_Reset();
    });
  }

  send_Reset () {
    const output = new this.pClass(this.output);
    const args = new Gatekeeper_Reset_args();
    try {
      output.writeMessageBegin('Reset', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_Reset (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_Reset_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  StopAll () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_StopAll();
    });
  }

  send_StopAll () {
    const output = new this.pClass(this.output);
    const args = new Gatekeeper_StopAll_args();
    try {
      output.writeMessageBegin('StopAll', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_StopAll (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_StopAll_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  SpontaneousCoreStatusChange (core, status) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_SpontaneousCoreStatusChange(core, status);
    });
  }

  send_SpontaneousCoreStatusChange (core, status) {
    const output = new this.pClass(this.output);
    const params = {
      core: core,
      status: status
    };
    const args = new Gatekeeper_SpontaneousCoreStatusChange_args(params);
    try {
      output.writeMessageBegin('SpontaneousCoreStatusChange', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_SpontaneousCoreStatusChange (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_SpontaneousCoreStatusChange_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  GetCoreStatus (core) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_GetCoreStatus(core);
    });
  }

  send_GetCoreStatus (core) {
    const output = new this.pClass(this.output);
    const params = {
      core: core
    };
    const args = new Gatekeeper_GetCoreStatus_args(params);
    try {
      output.writeMessageBegin('GetCoreStatus', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_GetCoreStatus (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_GetCoreStatus_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('GetCoreStatus failed: unknown result');
  }

  IsItOkToStopCore (core) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_IsItOkToStopCore(core);
    });
  }

  send_IsItOkToStopCore (core) {
    const output = new this.pClass(this.output);
    const params = {
      core: core
    };
    const args = new Gatekeeper_IsItOkToStopCore_args(params);
    try {
      output.writeMessageBegin('IsItOkToStopCore', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_IsItOkToStopCore (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_IsItOkToStopCore_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('IsItOkToStopCore failed: unknown result');
  }

  SetCPUStatusPolling (on) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_SetCPUStatusPolling(on);
    });
  }

  send_SetCPUStatusPolling (on) {
    const output = new this.pClass(this.output);
    const params = {
      on: on
    };
    const args = new Gatekeeper_SetCPUStatusPolling_args(params);
    try {
      output.writeMessageBegin('SetCPUStatusPolling', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_SetCPUStatusPolling (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_SetCPUStatusPolling_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  AckCPUStatusPolling (coreCount) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_AckCPUStatusPolling(coreCount);
    });
  }

  send_AckCPUStatusPolling (coreCount) {
    const output = new this.pClass(this.output);
    const params = {
      coreCount: coreCount
    };
    const args = new Gatekeeper_AckCPUStatusPolling_args(params);
    try {
      output.writeMessageBegin('AckCPUStatusPolling', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_AckCPUStatusPolling (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new Gatekeeper_AckCPUStatusPolling_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }
};
export { GatekeeperClient as Client };
const GatekeeperProcessor = class GatekeeperProcessor extends HeartbeatServiceProcessor {
  constructor(handler) {
    super(handler);
    this._handler = handler;
  }
  process (input, output) {
    const r = input.readMessageBegin();
    if (this['process_' + r.fname]) {
      return this['process_' + r.fname].call(this, r.rseqid, input, output);
    } else {
      input.skip(Thrift.Type.STRUCT);
      input.readMessageEnd();
      const x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
      output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
      x["write"](output);
      output.writeMessageEnd();
      output.flush();
    }
  }
  process_SetRunAllCores (seqid, input, output) {
    const args = new Gatekeeper_SetRunAllCores_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.SetRunAllCores.length === 1) {
      new Promise((resolve) => resolve(this._handler.SetRunAllCores.bind(this._handler)(
        args.all
      ))).then(result => {
        const result_obj = new Gatekeeper_SetRunAllCores_result({success: result});
        output.writeMessageBegin("SetRunAllCores", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SetRunAllCores", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.SetRunAllCores(args.all, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_SetRunAllCores_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("SetRunAllCores", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("SetRunAllCores", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_SetStartOneStartsAll (seqid, input, output) {
    const args = new Gatekeeper_SetStartOneStartsAll_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.SetStartOneStartsAll.length === 1) {
      new Promise((resolve) => resolve(this._handler.SetStartOneStartsAll.bind(this._handler)(
        args.on
      ))).then(result => {
        const result_obj = new Gatekeeper_SetStartOneStartsAll_result({success: result});
        output.writeMessageBegin("SetStartOneStartsAll", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SetStartOneStartsAll", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.SetStartOneStartsAll(args.on, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_SetStartOneStartsAll_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("SetStartOneStartsAll", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("SetStartOneStartsAll", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_SetSoftCTI (seqid, input, output) {
    const args = new Gatekeeper_SetSoftCTI_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.SetSoftCTI.length === 1) {
      new Promise((resolve) => resolve(this._handler.SetSoftCTI.bind(this._handler)(
        args.on
      ))).then(result => {
        const result_obj = new Gatekeeper_SetSoftCTI_result({success: result});
        output.writeMessageBegin("SetSoftCTI", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SetSoftCTI", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.SetSoftCTI(args.on, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_SetSoftCTI_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("SetSoftCTI", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("SetSoftCTI", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_BeforeLowLevelGo (seqid, input, output) {
    const args = new Gatekeeper_BeforeLowLevelGo_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.BeforeLowLevelGo.length === 2) {
      new Promise((resolve) => resolve(this._handler.BeforeLowLevelGo.bind(this._handler)(
        args.core,
        args.multi
      ))).then(result => {
        const result_obj = new Gatekeeper_BeforeLowLevelGo_result({success: result});
        output.writeMessageBegin("BeforeLowLevelGo", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("BeforeLowLevelGo", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.BeforeLowLevelGo(args.core, args.multi, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_BeforeLowLevelGo_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("BeforeLowLevelGo", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("BeforeLowLevelGo", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_StartedCPU (seqid, input, output) {
    const args = new Gatekeeper_StartedCPU_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.StartedCPU.length === 1) {
      new Promise((resolve) => resolve(this._handler.StartedCPU.bind(this._handler)(
        args.core
      ))).then(result => {
        const result_obj = new Gatekeeper_StartedCPU_result({success: result});
        output.writeMessageBegin("StartedCPU", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("StartedCPU", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.StartedCPU(args.core, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_StartedCPU_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("StartedCPU", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("StartedCPU", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_CPUStoped (seqid, input, output) {
    const args = new Gatekeeper_CPUStoped_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.CPUStoped.length === 1) {
      new Promise((resolve) => resolve(this._handler.CPUStoped.bind(this._handler)(
        args.core
      ))).then(result => {
        const result_obj = new Gatekeeper_CPUStoped_result({success: result});
        output.writeMessageBegin("CPUStoped", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("CPUStoped", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.CPUStoped(args.core, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_CPUStoped_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("CPUStoped", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("CPUStoped", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_IsTargetStopped (seqid, input, output) {
    const args = new Gatekeeper_IsTargetStopped_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.IsTargetStopped.length === 0) {
      new Promise((resolve) => resolve(this._handler.IsTargetStopped.bind(this._handler)(
      ))).then(result => {
        const result_obj = new Gatekeeper_IsTargetStopped_result({success: result});
        output.writeMessageBegin("IsTargetStopped", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("IsTargetStopped", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.IsTargetStopped((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_IsTargetStopped_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("IsTargetStopped", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("IsTargetStopped", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_AfterLowLevelGo (seqid, input, output) {
    const args = new Gatekeeper_AfterLowLevelGo_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.AfterLowLevelGo.length === 2) {
      new Promise((resolve) => resolve(this._handler.AfterLowLevelGo.bind(this._handler)(
        args.core,
        args.code
      ))).then(result => {
        const result_obj = new Gatekeeper_AfterLowLevelGo_result({success: result});
        output.writeMessageBegin("AfterLowLevelGo", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("AfterLowLevelGo", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.AfterLowLevelGo(args.core, args.code, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_AfterLowLevelGo_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("AfterLowLevelGo", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("AfterLowLevelGo", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_Reset (seqid, input, output) {
    const args = new Gatekeeper_Reset_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.Reset.length === 0) {
      new Promise((resolve) => resolve(this._handler.Reset.bind(this._handler)(
      ))).then(result => {
        const result_obj = new Gatekeeper_Reset_result({success: result});
        output.writeMessageBegin("Reset", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("Reset", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.Reset((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_Reset_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("Reset", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("Reset", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_StopAll (seqid, input, output) {
    const args = new Gatekeeper_StopAll_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.StopAll.length === 0) {
      new Promise((resolve) => resolve(this._handler.StopAll.bind(this._handler)(
      ))).then(result => {
        const result_obj = new Gatekeeper_StopAll_result({success: result});
        output.writeMessageBegin("StopAll", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("StopAll", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.StopAll((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_StopAll_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("StopAll", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("StopAll", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_SpontaneousCoreStatusChange (seqid, input, output) {
    const args = new Gatekeeper_SpontaneousCoreStatusChange_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.SpontaneousCoreStatusChange.length === 2) {
      new Promise((resolve) => resolve(this._handler.SpontaneousCoreStatusChange.bind(this._handler)(
        args.core,
        args.status
      ))).then(result => {
        const result_obj = new Gatekeeper_SpontaneousCoreStatusChange_result({success: result});
        output.writeMessageBegin("SpontaneousCoreStatusChange", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SpontaneousCoreStatusChange", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.SpontaneousCoreStatusChange(args.core, args.status, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_SpontaneousCoreStatusChange_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("SpontaneousCoreStatusChange", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("SpontaneousCoreStatusChange", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_GetCoreStatus (seqid, input, output) {
    const args = new Gatekeeper_GetCoreStatus_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.GetCoreStatus.length === 1) {
      new Promise((resolve) => resolve(this._handler.GetCoreStatus.bind(this._handler)(
        args.core
      ))).then(result => {
        const result_obj = new Gatekeeper_GetCoreStatus_result({success: result});
        output.writeMessageBegin("GetCoreStatus", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetCoreStatus", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.GetCoreStatus(args.core, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_GetCoreStatus_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("GetCoreStatus", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("GetCoreStatus", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_IsItOkToStopCore (seqid, input, output) {
    const args = new Gatekeeper_IsItOkToStopCore_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.IsItOkToStopCore.length === 1) {
      new Promise((resolve) => resolve(this._handler.IsItOkToStopCore.bind(this._handler)(
        args.core
      ))).then(result => {
        const result_obj = new Gatekeeper_IsItOkToStopCore_result({success: result});
        output.writeMessageBegin("IsItOkToStopCore", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("IsItOkToStopCore", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.IsItOkToStopCore(args.core, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_IsItOkToStopCore_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("IsItOkToStopCore", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("IsItOkToStopCore", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_SetCPUStatusPolling (seqid, input, output) {
    const args = new Gatekeeper_SetCPUStatusPolling_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.SetCPUStatusPolling.length === 1) {
      new Promise((resolve) => resolve(this._handler.SetCPUStatusPolling.bind(this._handler)(
        args.on
      ))).then(result => {
        const result_obj = new Gatekeeper_SetCPUStatusPolling_result({success: result});
        output.writeMessageBegin("SetCPUStatusPolling", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SetCPUStatusPolling", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.SetCPUStatusPolling(args.on, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_SetCPUStatusPolling_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("SetCPUStatusPolling", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("SetCPUStatusPolling", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_AckCPUStatusPolling (seqid, input, output) {
    const args = new Gatekeeper_AckCPUStatusPolling_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.AckCPUStatusPolling.length === 1) {
      new Promise((resolve) => resolve(this._handler.AckCPUStatusPolling.bind(this._handler)(
        args.coreCount
      ))).then(result => {
        const result_obj = new Gatekeeper_AckCPUStatusPolling_result({success: result});
        output.writeMessageBegin("AckCPUStatusPolling", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("AckCPUStatusPolling", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.AckCPUStatusPolling(args.coreCount, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new Gatekeeper_AckCPUStatusPolling_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("AckCPUStatusPolling", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("AckCPUStatusPolling", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
};
export { GatekeeperProcessor as Processor };
