//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Int64 = require('node-int64');
import { v4 as uuid } from 'uuid';
type uuid = string;

import ttypes = require('./libsupport_types');
import LIBSUPPORT_SERVICE = ttypes.LIBSUPPORT_SERVICE

/**
 * This service redirects the I/O streams of the program being
 * debugged by C-SPY towards the environment hosting C-SPY itself.
 */
declare class Client {
    private output: thrift.TTransport;
    private pClass: thrift.TProtocol;
    private _seqid: number;

    constructor(output: thrift.TTransport, pClass: { new(trans: thrift.TTransport): thrift.TProtocol });

    /**
     * Request input from the terminal I/O console.
     */
    requestInputBinary(len: number): Promise<Buffer>;

    /**
     * Request input from the terminal I/O console.
     */
    requestInputBinary(len: number, callback?: (error: void, response: Buffer)=>void): void;

    /**
     * @deprecated, use requestInputBinary instead
     */
    requestInput(len: number): Promise<string>;

    /**
     * @deprecated, use requestInputBinary instead
     */
    requestInput(len: number, callback?: (error: void, response: string)=>void): void;

    /**
     * Handle output from the target program.
     */
    printOutputBinary(data: Buffer): Promise<void>;

    /**
     * Handle output from the target program.
     */
    printOutputBinary(data: Buffer, callback?: (error: void, response: void)=>void): void;

    /**
     * @deprecated, use printOutputBinary instead
     */
    printOutput(data: string): Promise<void>;

    /**
     * @deprecated, use printOutputBinary instead
     */
    printOutput(data: string, callback?: (error: void, response: void)=>void): void;

    /**
     * The target program has exited.
     */
    exit(code: number): Promise<void>;

    /**
     * The target program has exited.
     */
    exit(code: number, callback?: (error: void, response: void)=>void): void;

    /**
     * The target program has aborted (i.e. called abort()).
     */
    reportAssert(file: string, line: string, message: string): Promise<void>;

    /**
     * The target program has aborted (i.e. called abort()).
     */
    reportAssert(file: string, line: string, message: string, callback?: (error: void, response: void)=>void): void;
  }

declare class Processor {
  private _handler: object;

  constructor(handler: object);
  process(input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_requestInputBinary(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_requestInput(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_printOutputBinary(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_printOutput(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_exit(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_reportAssert(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
}
