//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';
import * as shared_ttypes from './shared_types.js';


import * as ttypes from './memory_types.js';
export const CSpyMemoryBlock = class {
  constructor(args) {
    this.data = null;
    this.status = null;
    if (args) {
      if (args.data !== undefined && args.data !== null) {
        this.data = args.data;
      }
      if (args.status !== undefined && args.status !== null) {
        this.status = args.status;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.data = input.readBinary();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRING) {
            this.status = input.readBinary();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CSpyMemoryBlock');
      if (this.data !== null && this.data !== undefined) {
        output.writeFieldBegin('data', Thrift.Type.STRING, 1);
        output.writeBinary(this.data);
        output.writeFieldEnd();
      }
      if (this.status !== null && this.status !== undefined) {
        output.writeFieldBegin('status', Thrift.Type.STRING, 2);
        output.writeBinary(this.status);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
