//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';
import * as shared_ttypes from './shared_types.js';
import * as projectmanager_ttypes from './projectmanager_types.js';


import * as ttypes from './OptionsService_types.js';
export const OptionsServiceError = class extends Thrift.TException {
  constructor(args) {
    super("OptionsServiceError");
    this.name = "OptionsServiceError";
    this.description = null;
    if (args) {
      if (args.description !== undefined && args.description !== null) {
        this.description = args.description;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.description = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('OptionsServiceError');
      if (this.description !== null && this.description !== undefined) {
        output.writeFieldBegin('description', Thrift.Type.STRING, 1);
        output.writeString(this.description);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const CreateSessionRequest = class {
  constructor(args) {
    this.projectPath = null;
    this.configurationName = null;
    this.nodePathOrIndex = null;
    this.showHiddenOptions = null;
    if (args) {
      if (args.projectPath !== undefined && args.projectPath !== null) {
        this.projectPath = args.projectPath;
      }
      if (args.configurationName !== undefined && args.configurationName !== null) {
        this.configurationName = args.configurationName;
      }
      if (args.nodePathOrIndex !== undefined && args.nodePathOrIndex !== null) {
        this.nodePathOrIndex = args.nodePathOrIndex;
      }
      if (args.showHiddenOptions !== undefined && args.showHiddenOptions !== null) {
        this.showHiddenOptions = args.showHiddenOptions;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.projectPath = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRING) {
            this.configurationName = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 4:
          if (ftype == Thrift.Type.STRING) {
            this.nodePathOrIndex = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.BOOL) {
            this.showHiddenOptions = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CreateSessionRequest');
      if (this.projectPath !== null && this.projectPath !== undefined) {
        output.writeFieldBegin('projectPath', Thrift.Type.STRING, 1);
        output.writeString(this.projectPath);
        output.writeFieldEnd();
      }
      if (this.configurationName !== null && this.configurationName !== undefined) {
        output.writeFieldBegin('configurationName', Thrift.Type.STRING, 2);
        output.writeString(this.configurationName);
        output.writeFieldEnd();
      }
      if (this.nodePathOrIndex !== null && this.nodePathOrIndex !== undefined) {
        output.writeFieldBegin('nodePathOrIndex', Thrift.Type.STRING, 4);
        output.writeString(this.nodePathOrIndex);
        output.writeFieldEnd();
      }
      if (this.showHiddenOptions !== null && this.showHiddenOptions !== undefined) {
        output.writeFieldBegin('showHiddenOptions', Thrift.Type.BOOL, 3);
        output.writeBool(this.showHiddenOptions);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const CreateSessionResponse = class {
  constructor(args) {
    this.sessionId = null;
    this.success = null;
    this.context = null;
    this.readOnly = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
      if (args.success !== undefined && args.success !== null) {
        this.success = new shared_ttypes.Success(args.success);
      }
      if (args.context !== undefined && args.context !== null) {
        this.context = new projectmanager_ttypes.ProjectContext(args.context);
      }
      if (args.readOnly !== undefined && args.readOnly !== null) {
        this.readOnly = args.readOnly;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new shared_ttypes.Success();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.STRUCT) {
            this.context = new projectmanager_ttypes.ProjectContext();
            this.context["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 4:
          if (ftype == Thrift.Type.BOOL) {
            this.readOnly = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CreateSessionResponse');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 2);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      if (this.context !== null && this.context !== undefined) {
        output.writeFieldBegin('context', Thrift.Type.STRUCT, 3);
        this.context["write"](output);
        output.writeFieldEnd();
      }
      if (this.readOnly !== null && this.readOnly !== undefined) {
        output.writeFieldBegin('readOnly', Thrift.Type.BOOL, 4);
        output.writeBool(this.readOnly);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const DestroySessionRequest = class {
  constructor(args) {
    this.sessionId = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('DestroySessionRequest');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const DestroySessionResponse = class {
  constructor(args) {
    this.sessionId = null;
    this.success = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
      if (args.success !== undefined && args.success !== null) {
        this.success = new shared_ttypes.Success(args.success);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new shared_ttypes.Success();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('DestroySessionResponse');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 2);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const Tree = class {
  constructor(args) {
    this.id = null;
    this.data = null;
    if (args) {
      if (args.id !== undefined && args.id !== null) {
        this.id = new shared_ttypes.Id(args.id);
      }
      if (args.data !== undefined && args.data !== null) {
        this.data = args.data;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.id = new shared_ttypes.Id();
            this.id["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRING) {
            this.data = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('Tree');
      if (this.id !== null && this.id !== undefined) {
        output.writeFieldBegin('id', Thrift.Type.STRUCT, 1);
        this.id["write"](output);
        output.writeFieldEnd();
      }
      if (this.data !== null && this.data !== undefined) {
        output.writeFieldBegin('data', Thrift.Type.STRING, 2);
        output.writeString(this.data);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const GetCategoryTreeRequest = class {
  constructor(args) {
    this.sessionId = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('GetCategoryTreeRequest');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const GetCategoryTreeResponse = class {
  constructor(args) {
    this.sessionId = null;
    this.tree = null;
    this.success = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
      if (args.tree !== undefined && args.tree !== null) {
        this.tree = new ttypes.Tree(args.tree);
      }
      if (args.success !== undefined && args.success !== null) {
        this.success = new shared_ttypes.Success(args.success);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.tree = new ttypes.Tree();
            this.tree["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new shared_ttypes.Success();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('GetCategoryTreeResponse');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      if (this.tree !== null && this.tree !== undefined) {
        output.writeFieldBegin('tree', Thrift.Type.STRUCT, 2);
        this.tree["write"](output);
        output.writeFieldEnd();
      }
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 3);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const GetOptionTreeRequest = class {
  constructor(args) {
    this.sessionId = null;
    this.treeId = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
      if (args.treeId !== undefined && args.treeId !== null) {
        this.treeId = new shared_ttypes.Id(args.treeId);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.treeId = new shared_ttypes.Id();
            this.treeId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('GetOptionTreeRequest');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      if (this.treeId !== null && this.treeId !== undefined) {
        output.writeFieldBegin('treeId', Thrift.Type.STRUCT, 2);
        this.treeId["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const GetOptionTreeResponse = class {
  constructor(args) {
    this.sessionId = null;
    this.tree = null;
    this.success = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
      if (args.tree !== undefined && args.tree !== null) {
        this.tree = new ttypes.Tree(args.tree);
      }
      if (args.success !== undefined && args.success !== null) {
        this.success = new shared_ttypes.Success(args.success);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.tree = new ttypes.Tree();
            this.tree["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new shared_ttypes.Success();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('GetOptionTreeResponse');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      if (this.tree !== null && this.tree !== undefined) {
        output.writeFieldBegin('tree', Thrift.Type.STRUCT, 2);
        this.tree["write"](output);
        output.writeFieldEnd();
      }
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 3);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const OptionValue = class {
  constructor(args) {
    this.optionDefinitionId = null;
    this.data = null;
    this.children = null;
    this.inherited = null;
    if (args) {
      if (args.optionDefinitionId !== undefined && args.optionDefinitionId !== null) {
        this.optionDefinitionId = args.optionDefinitionId;
      }
      if (args.data !== undefined && args.data !== null) {
        this.data = args.data;
      }
      if (args.children !== undefined && args.children !== null) {
        this.children = Thrift.copyList(args.children, [null]);
      }
      if (args.inherited !== undefined && args.inherited !== null) {
        this.inherited = args.inherited;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.optionDefinitionId = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRING) {
            this.data = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.LIST) {
            this.children = [];
            const _rtmp31 = input.readListBegin();
            const _size0 = _rtmp31.size || 0;
            for (let _i2 = 0; _i2 < _size0; ++_i2) {
              let elem3 = null;
              elem3 = new ttypes.OptionValue();
              elem3["read"](input);
              this.children.push(elem3);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 4:
          if (ftype == Thrift.Type.BOOL) {
            this.inherited = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('OptionValue');
      if (this.optionDefinitionId !== null && this.optionDefinitionId !== undefined) {
        output.writeFieldBegin('optionDefinitionId', Thrift.Type.STRING, 1);
        output.writeString(this.optionDefinitionId);
        output.writeFieldEnd();
      }
      if (this.data !== null && this.data !== undefined) {
        output.writeFieldBegin('data', Thrift.Type.STRING, 2);
        output.writeString(this.data);
        output.writeFieldEnd();
      }
      if (this.children !== null && this.children !== undefined) {
        output.writeFieldBegin('children', Thrift.Type.LIST, 3);
        output.writeListBegin(Thrift.Type.STRUCT, this.children.length);
        for (let iter4 in this.children) {
          if (this.children.hasOwnProperty(iter4)) {
            iter4 = this.children[iter4];
            iter4["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      if (this.inherited !== null && this.inherited !== undefined) {
        output.writeFieldBegin('inherited', Thrift.Type.BOOL, 4);
        output.writeBool(this.inherited);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const VerificationError = class {
  constructor(args) {
    this.optionDefinitionId = null;
    this.errorMessage = null;
    if (args) {
      if (args.optionDefinitionId !== undefined && args.optionDefinitionId !== null) {
        this.optionDefinitionId = args.optionDefinitionId;
      }
      if (args.errorMessage !== undefined && args.errorMessage !== null) {
        this.errorMessage = args.errorMessage;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRING) {
            this.optionDefinitionId = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRING) {
            this.errorMessage = input.readString();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('VerificationError');
      if (this.optionDefinitionId !== null && this.optionDefinitionId !== undefined) {
        output.writeFieldBegin('optionDefinitionId', Thrift.Type.STRING, 1);
        output.writeString(this.optionDefinitionId);
        output.writeFieldEnd();
      }
      if (this.errorMessage !== null && this.errorMessage !== undefined) {
        output.writeFieldBegin('errorMessage', Thrift.Type.STRING, 2);
        output.writeString(this.errorMessage);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const UpdateOptionsStateRequest = class {
  constructor(args) {
    this.sessionId = null;
    this.treeId = null;
    this.createdOptionValues = null;
    this.updatedOptionValues = null;
    this.deletedOptionValues = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
      if (args.treeId !== undefined && args.treeId !== null) {
        this.treeId = new shared_ttypes.Id(args.treeId);
      }
      if (args.createdOptionValues !== undefined && args.createdOptionValues !== null) {
        this.createdOptionValues = Thrift.copyList(args.createdOptionValues, [ttypes.OptionValue]);
      }
      if (args.updatedOptionValues !== undefined && args.updatedOptionValues !== null) {
        this.updatedOptionValues = Thrift.copyList(args.updatedOptionValues, [ttypes.OptionValue]);
      }
      if (args.deletedOptionValues !== undefined && args.deletedOptionValues !== null) {
        this.deletedOptionValues = Thrift.copyList(args.deletedOptionValues, [ttypes.OptionValue]);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.treeId = new shared_ttypes.Id();
            this.treeId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.LIST) {
            this.createdOptionValues = [];
            const _rtmp36 = input.readListBegin();
            const _size5 = _rtmp36.size || 0;
            for (let _i7 = 0; _i7 < _size5; ++_i7) {
              let elem8 = null;
              elem8 = new ttypes.OptionValue();
              elem8["read"](input);
              this.createdOptionValues.push(elem8);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 4:
          if (ftype == Thrift.Type.LIST) {
            this.updatedOptionValues = [];
            const _rtmp310 = input.readListBegin();
            const _size9 = _rtmp310.size || 0;
            for (let _i11 = 0; _i11 < _size9; ++_i11) {
              let elem12 = null;
              elem12 = new ttypes.OptionValue();
              elem12["read"](input);
              this.updatedOptionValues.push(elem12);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 5:
          if (ftype == Thrift.Type.LIST) {
            this.deletedOptionValues = [];
            const _rtmp314 = input.readListBegin();
            const _size13 = _rtmp314.size || 0;
            for (let _i15 = 0; _i15 < _size13; ++_i15) {
              let elem16 = null;
              elem16 = new ttypes.OptionValue();
              elem16["read"](input);
              this.deletedOptionValues.push(elem16);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('UpdateOptionsStateRequest');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      if (this.treeId !== null && this.treeId !== undefined) {
        output.writeFieldBegin('treeId', Thrift.Type.STRUCT, 2);
        this.treeId["write"](output);
        output.writeFieldEnd();
      }
      if (this.createdOptionValues !== null && this.createdOptionValues !== undefined) {
        output.writeFieldBegin('createdOptionValues', Thrift.Type.LIST, 3);
        output.writeListBegin(Thrift.Type.STRUCT, this.createdOptionValues.length);
        for (let iter17 in this.createdOptionValues) {
          if (this.createdOptionValues.hasOwnProperty(iter17)) {
            iter17 = this.createdOptionValues[iter17];
            iter17["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      if (this.updatedOptionValues !== null && this.updatedOptionValues !== undefined) {
        output.writeFieldBegin('updatedOptionValues', Thrift.Type.LIST, 4);
        output.writeListBegin(Thrift.Type.STRUCT, this.updatedOptionValues.length);
        for (let iter18 in this.updatedOptionValues) {
          if (this.updatedOptionValues.hasOwnProperty(iter18)) {
            iter18 = this.updatedOptionValues[iter18];
            iter18["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      if (this.deletedOptionValues !== null && this.deletedOptionValues !== undefined) {
        output.writeFieldBegin('deletedOptionValues', Thrift.Type.LIST, 5);
        output.writeListBegin(Thrift.Type.STRUCT, this.deletedOptionValues.length);
        for (let iter19 in this.deletedOptionValues) {
          if (this.deletedOptionValues.hasOwnProperty(iter19)) {
            iter19 = this.deletedOptionValues[iter19];
            iter19["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const UpdateOptionsStateResponse = class {
  constructor(args) {
    this.sessionId = null;
    this.tree = null;
    this.success = null;
    this.verificationErrors = null;
    this.categoryTreeInvalidated = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
      if (args.tree !== undefined && args.tree !== null) {
        this.tree = new ttypes.Tree(args.tree);
      }
      if (args.success !== undefined && args.success !== null) {
        this.success = new shared_ttypes.Success(args.success);
      }
      if (args.verificationErrors !== undefined && args.verificationErrors !== null) {
        this.verificationErrors = Thrift.copyList(args.verificationErrors, [ttypes.VerificationError]);
      }
      if (args.categoryTreeInvalidated !== undefined && args.categoryTreeInvalidated !== null) {
        this.categoryTreeInvalidated = args.categoryTreeInvalidated;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.tree = new ttypes.Tree();
            this.tree["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 3:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new shared_ttypes.Success();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 4:
          if (ftype == Thrift.Type.LIST) {
            this.verificationErrors = [];
            const _rtmp321 = input.readListBegin();
            const _size20 = _rtmp321.size || 0;
            for (let _i22 = 0; _i22 < _size20; ++_i22) {
              let elem23 = null;
              elem23 = new ttypes.VerificationError();
              elem23["read"](input);
              this.verificationErrors.push(elem23);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 5:
          if (ftype == Thrift.Type.BOOL) {
            this.categoryTreeInvalidated = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('UpdateOptionsStateResponse');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      if (this.tree !== null && this.tree !== undefined) {
        output.writeFieldBegin('tree', Thrift.Type.STRUCT, 2);
        this.tree["write"](output);
        output.writeFieldEnd();
      }
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 3);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      if (this.verificationErrors !== null && this.verificationErrors !== undefined) {
        output.writeFieldBegin('verificationErrors', Thrift.Type.LIST, 4);
        output.writeListBegin(Thrift.Type.STRUCT, this.verificationErrors.length);
        for (let iter24 in this.verificationErrors) {
          if (this.verificationErrors.hasOwnProperty(iter24)) {
            iter24 = this.verificationErrors[iter24];
            iter24["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      if (this.categoryTreeInvalidated !== null && this.categoryTreeInvalidated !== undefined) {
        output.writeFieldBegin('categoryTreeInvalidated', Thrift.Type.BOOL, 5);
        output.writeBool(this.categoryTreeInvalidated);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const CommitOptionStateRequest = class {
  constructor(args) {
    this.sessionId = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CommitOptionStateRequest');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const CommitOptionStateResponse = class {
  constructor(args) {
    this.sessionId = null;
    this.success = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new shared_ttypes.Id(args.sessionId);
      }
      if (args.success !== undefined && args.success !== null) {
        this.success = new shared_ttypes.Success(args.success);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.sessionId = new shared_ttypes.Id();
            this.sessionId["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 2:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new shared_ttypes.Success();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('CommitOptionStateResponse');
      if (this.sessionId !== null && this.sessionId !== undefined) {
        output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
        this.sessionId["write"](output);
        output.writeFieldEnd();
      }
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 2);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
export const SERVICE_ID = 'com.iar.optionsservice';
export const BUILD_ACTION_BUILD_SEQUENCE_OPTION_ID = 'BUILDACTION.BuildActions.BuildSequence';
export const BUILD_ACTION_COMMAND_LINE_OPTION_ID = 'BUILDACTION.BuildActions.CommandLine';
export const BUILD_ACTION_DEPENDENCIES_OPTION_ID = 'BUILDACTION.BuildActions.Dependencies';
export const BUILD_ACTION_OUTPUTS_OPTION_ID = 'BUILDACTION.BuildActions.Outputs';
export const BUILD_ACTION_WORKING_DIRECTORY_OPTION_ID = 'BUILDACTION.BuildActions.WorkingDirectory';
