//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Int64 = require('node-int64');
import { v4 as uuid } from 'uuid';
type uuid = string;
import shared_ttypes = require('./shared_types.js');
import projectmanager_ttypes = require('./projectmanager_types.js');



declare class OptionsServiceError extends Thrift.TException {
    public description: string;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { description: string; });
  }

declare class CreateSessionRequest {
    public projectPath: string;
    public configurationName: string;
    public nodePathOrIndex: string;
    public showHiddenOptions: boolean;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { projectPath: string; configurationName: string; nodePathOrIndex: string; showHiddenOptions: boolean; });
  }

declare class CreateSessionResponse {
    public sessionId: shared_ttypes.Id;
    public success: shared_ttypes.Success;
    public context: projectmanager_ttypes.ProjectContext;
    public readOnly: boolean;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; success: shared_ttypes.Success; context: projectmanager_ttypes.ProjectContext; readOnly: boolean; });
  }

declare class DestroySessionRequest {
    public sessionId: shared_ttypes.Id;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; });
  }

declare class DestroySessionResponse {
    public sessionId: shared_ttypes.Id;
    public success: shared_ttypes.Success;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; success: shared_ttypes.Success; });
  }

declare class Tree {
    public id: shared_ttypes.Id;
    public data: string;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { id: shared_ttypes.Id; data: string; });
  }

declare class GetCategoryTreeRequest {
    public sessionId: shared_ttypes.Id;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; });
  }

declare class GetCategoryTreeResponse {
    public sessionId: shared_ttypes.Id;
    public tree: Tree;
    public success: shared_ttypes.Success;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; tree: Tree; success: shared_ttypes.Success; });
  }

declare class GetOptionTreeRequest {
    public sessionId: shared_ttypes.Id;
    public treeId: shared_ttypes.Id;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; treeId: shared_ttypes.Id; });
  }

declare class GetOptionTreeResponse {
    public sessionId: shared_ttypes.Id;
    public tree: Tree;
    public success: shared_ttypes.Success;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; tree: Tree; success: shared_ttypes.Success; });
  }

declare class OptionValue {
    public optionDefinitionId: string;
    public data: string;
    public children: OptionValue[];
    public inherited: boolean;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { optionDefinitionId: string; data: string; children: OptionValue[]; inherited: boolean; });
  }

declare class VerificationError {
    public optionDefinitionId: string;
    public errorMessage: string;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { optionDefinitionId: string; errorMessage: string; });
  }

declare class UpdateOptionsStateRequest {
    public sessionId: shared_ttypes.Id;
    public treeId: shared_ttypes.Id;
    public createdOptionValues: OptionValue[];
    public updatedOptionValues: OptionValue[];
    public deletedOptionValues: OptionValue[];

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; treeId: shared_ttypes.Id; createdOptionValues: OptionValue[]; updatedOptionValues: OptionValue[]; deletedOptionValues: OptionValue[]; });
  }

declare class UpdateOptionsStateResponse {
    public sessionId: shared_ttypes.Id;
    public tree: Tree;
    public success: shared_ttypes.Success;
    public verificationErrors: VerificationError[];
    public categoryTreeInvalidated: boolean;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; tree: Tree; success: shared_ttypes.Success; verificationErrors: VerificationError[]; categoryTreeInvalidated: boolean; });
  }

declare class CommitOptionStateRequest {
    public sessionId: shared_ttypes.Id;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; });
  }

declare class CommitOptionStateResponse {
    public sessionId: shared_ttypes.Id;
    public success: shared_ttypes.Success;

      read(input: object): void;
  write(output: object): void;
  constructor(args?: { sessionId: shared_ttypes.Id; success: shared_ttypes.Success; });
  }

declare const SERVICE_ID: string;

declare const BUILD_ACTION_BUILD_SEQUENCE_OPTION_ID: string;

declare const BUILD_ACTION_COMMAND_LINE_OPTION_ID: string;

declare const BUILD_ACTION_DEPENDENCIES_OPTION_ID: string;

declare const BUILD_ACTION_OUTPUTS_OPTION_ID: string;

declare const BUILD_ACTION_WORKING_DIRECTORY_OPTION_ID: string;
