//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';
import * as shared_ttypes from './shared_types.js';
import * as cspy_ttypes from './cspy_types.js';
import * as ServiceRegistry_ttypes from './ServiceRegistry_types.js';


import * as HeartbeatService from './HeartbeatService.js';
const HeartbeatServiceClient = HeartbeatService.Client;
const HeartbeatServiceProcessor = HeartbeatService.Processor;
import * as ttypes from './ampsync_types.js';
//HELPER FUNCTIONS AND STRUCTURES

const PartnerRegistry_GetAllPartners_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_GetAllPartners_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_GetAllPartners_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = Thrift.copyList(args.success, [ttypes.PartnerInformation]);
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.LIST) {
            this.success = [];
            const _rtmp315 = input.readListBegin();
            const _size14 = _rtmp315.size || 0;
            for (let _i16 = 0; _i16 < _size14; ++_i16) {
              let elem17 = null;
              elem17 = new ttypes.PartnerInformation();
              elem17["read"](input);
              this.success.push(elem17);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_GetAllPartners_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.LIST, 0);
        output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
        for (let iter18 in this.success) {
          if (this.success.hasOwnProperty(iter18)) {
            iter18 = this.success[iter18];
            iter18["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_GetPartnerInfo_args = class {
  constructor(args) {
    this.who = null;
    if (args) {
      if (args.who !== undefined && args.who !== null) {
        this.who = args.who;
      } else {
        throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field who is unset!');
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.who = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_GetPartnerInfo_args');
      if (this.who !== null && this.who !== undefined) {
        output.writeFieldBegin('who', Thrift.Type.I32, 1);
        output.writeI32(this.who);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_GetPartnerInfo_result = class {
  constructor(args) {
    this.success = null;
    this.partner = null;
    if (args instanceof ttypes.UnknownPartner) {
        this.partner = args;
        return;
    }
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = new ttypes.PartnerInformation(args.success);
      }
      if (args.partner !== undefined && args.partner !== null) {
        this.partner = args.partner;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.STRUCT) {
            this.success = new ttypes.PartnerInformation();
            this.success["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.partner = new ttypes.UnknownPartner();
            this.partner["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_GetPartnerInfo_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
        this.success["write"](output);
        output.writeFieldEnd();
      }
      if (this.partner !== null && this.partner !== undefined) {
        output.writeFieldBegin('partner', Thrift.Type.STRUCT, 1);
        this.partner["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_AcknowledgePartnerIsAlive_args = class {
  constructor(args) {
    this.myId = null;
    if (args) {
      if (args.myId !== undefined && args.myId !== null) {
        this.myId = args.myId;
      } else {
        throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field myId is unset!');
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.myId = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_AcknowledgePartnerIsAlive_args');
      if (this.myId !== null && this.myId !== undefined) {
        output.writeFieldBegin('myId', Thrift.Type.I32, 1);
        output.writeI32(this.myId);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_AcknowledgePartnerIsAlive_result = class {
  constructor(args) {
    this.partner = null;
    if (args instanceof ttypes.UnknownPartner) {
        this.partner = args;
        return;
    }
    if (args) {
      if (args.partner !== undefined && args.partner !== null) {
        this.partner = args.partner;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.partner = new ttypes.UnknownPartner();
            this.partner["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_AcknowledgePartnerIsAlive_result');
      if (this.partner !== null && this.partner !== undefined) {
        output.writeFieldBegin('partner', Thrift.Type.STRUCT, 1);
        this.partner["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_IsPartnerAlive_args = class {
  constructor(args) {
    this.who = null;
    if (args) {
      if (args.who !== undefined && args.who !== null) {
        this.who = args.who;
      } else {
        throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field who is unset!');
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.who = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_IsPartnerAlive_args');
      if (this.who !== null && this.who !== undefined) {
        output.writeFieldBegin('who', Thrift.Type.I32, 1);
        output.writeI32(this.who);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_IsPartnerAlive_result = class {
  constructor(args) {
    this.success = null;
    this.partner = null;
    if (args instanceof ttypes.UnknownPartner) {
        this.partner = args;
        return;
    }
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
      if (args.partner !== undefined && args.partner !== null) {
        this.partner = args.partner;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.BOOL) {
            this.success = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.partner = new ttypes.UnknownPartner();
            this.partner["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_IsPartnerAlive_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
        output.writeBool(this.success);
        output.writeFieldEnd();
      }
      if (this.partner !== null && this.partner !== undefined) {
        output.writeFieldBegin('partner', Thrift.Type.STRUCT, 1);
        this.partner["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_SetPartnerInfo_args = class {
  constructor(args) {
    this.information = null;
    if (args) {
      if (args.information !== undefined && args.information !== null) {
        this.information = new ttypes.PartnerInformation(args.information);
      } else {
        throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field information is unset!');
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.STRUCT) {
            this.information = new ttypes.PartnerInformation();
            this.information["read"](input);
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_SetPartnerInfo_args');
      if (this.information !== null && this.information !== undefined) {
        output.writeFieldBegin('information', Thrift.Type.STRUCT, 1);
        this.information["write"](output);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_SetPartnerInfo_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_SetPartnerInfo_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_SetAllPartners_args = class {
  constructor(args) {
    this.allPartners = null;
    if (args) {
      if (args.allPartners !== undefined && args.allPartners !== null) {
        this.allPartners = Thrift.copyList(args.allPartners, [ttypes.PartnerInformation]);
      } else {
        throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field allPartners is unset!');
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.LIST) {
            this.allPartners = [];
            const _rtmp320 = input.readListBegin();
            const _size19 = _rtmp320.size || 0;
            for (let _i21 = 0; _i21 < _size19; ++_i21) {
              let elem22 = null;
              elem22 = new ttypes.PartnerInformation();
              elem22["read"](input);
              this.allPartners.push(elem22);
            }
            input.readListEnd();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_SetAllPartners_args');
      if (this.allPartners !== null && this.allPartners !== undefined) {
        output.writeFieldBegin('allPartners', Thrift.Type.LIST, 1);
        output.writeListBegin(Thrift.Type.STRUCT, this.allPartners.length);
        for (let iter23 in this.allPartners) {
          if (this.allPartners.hasOwnProperty(iter23)) {
            iter23 = this.allPartners[iter23];
            iter23["write"](output);
          }
        }
        output.writeListEnd();
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistry_SetAllPartners_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('PartnerRegistry_SetAllPartners_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const PartnerRegistryClient = class PartnerRegistryClient extends HeartbeatServiceClient {
  constructor(output, pClass) {
    super(output, pClass);
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
  }
  seqid () { return this._seqid; }
  new_seqid () { return this._seqid += 1; }

  GetAllPartners () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_GetAllPartners();
    });
  }

  send_GetAllPartners () {
    const output = new this.pClass(this.output);
    const args = new PartnerRegistry_GetAllPartners_args();
    try {
      output.writeMessageBegin('GetAllPartners', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_GetAllPartners (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new PartnerRegistry_GetAllPartners_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('GetAllPartners failed: unknown result');
  }

  GetPartnerInfo (who) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_GetPartnerInfo(who);
    });
  }

  send_GetPartnerInfo (who) {
    const output = new this.pClass(this.output);
    const params = {
      who: who
    };
    const args = new PartnerRegistry_GetPartnerInfo_args(params);
    try {
      output.writeMessageBegin('GetPartnerInfo', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_GetPartnerInfo (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new PartnerRegistry_GetPartnerInfo_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.partner) {
      return callback(result.partner);
    }
    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('GetPartnerInfo failed: unknown result');
  }

  AcknowledgePartnerIsAlive (myId) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_AcknowledgePartnerIsAlive(myId);
    });
  }

  send_AcknowledgePartnerIsAlive (myId) {
    const output = new this.pClass(this.output);
    const params = {
      myId: myId
    };
    const args = new PartnerRegistry_AcknowledgePartnerIsAlive_args(params);
    try {
      output.writeMessageBegin('AcknowledgePartnerIsAlive', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_AcknowledgePartnerIsAlive (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new PartnerRegistry_AcknowledgePartnerIsAlive_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.partner) {
      return callback(result.partner);
    }
    callback(null);
  }

  IsPartnerAlive (who) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_IsPartnerAlive(who);
    });
  }

  send_IsPartnerAlive (who) {
    const output = new this.pClass(this.output);
    const params = {
      who: who
    };
    const args = new PartnerRegistry_IsPartnerAlive_args(params);
    try {
      output.writeMessageBegin('IsPartnerAlive', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_IsPartnerAlive (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new PartnerRegistry_IsPartnerAlive_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.partner) {
      return callback(result.partner);
    }
    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('IsPartnerAlive failed: unknown result');
  }

  SetPartnerInfo (information) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_SetPartnerInfo(information);
    });
  }

  send_SetPartnerInfo (information) {
    const output = new this.pClass(this.output);
    const params = {
      information: information
    };
    const args = new PartnerRegistry_SetPartnerInfo_args(params);
    try {
      output.writeMessageBegin('SetPartnerInfo', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_SetPartnerInfo (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new PartnerRegistry_SetPartnerInfo_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  SetAllPartners (allPartners) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_SetAllPartners(allPartners);
    });
  }

  send_SetAllPartners (allPartners) {
    const output = new this.pClass(this.output);
    const params = {
      allPartners: allPartners
    };
    const args = new PartnerRegistry_SetAllPartners_args(params);
    try {
      output.writeMessageBegin('SetAllPartners', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_SetAllPartners (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new PartnerRegistry_SetAllPartners_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }
};
export { PartnerRegistryClient as Client };
const PartnerRegistryProcessor = class PartnerRegistryProcessor extends HeartbeatServiceProcessor {
  constructor(handler) {
    super(handler);
    this._handler = handler;
  }
  process (input, output) {
    const r = input.readMessageBegin();
    if (this['process_' + r.fname]) {
      return this['process_' + r.fname].call(this, r.rseqid, input, output);
    } else {
      input.skip(Thrift.Type.STRUCT);
      input.readMessageEnd();
      const x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
      output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
      x["write"](output);
      output.writeMessageEnd();
      output.flush();
    }
  }
  process_GetAllPartners (seqid, input, output) {
    const args = new PartnerRegistry_GetAllPartners_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.GetAllPartners.length === 0) {
      new Promise((resolve) => resolve(this._handler.GetAllPartners.bind(this._handler)(
      ))).then(result => {
        const result_obj = new PartnerRegistry_GetAllPartners_result({success: result});
        output.writeMessageBegin("GetAllPartners", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetAllPartners", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.GetAllPartners((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new PartnerRegistry_GetAllPartners_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("GetAllPartners", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("GetAllPartners", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_GetPartnerInfo (seqid, input, output) {
    const args = new PartnerRegistry_GetPartnerInfo_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.GetPartnerInfo.length === 1) {
      new Promise((resolve) => resolve(this._handler.GetPartnerInfo.bind(this._handler)(
        args.who
      ))).then(result => {
        const result_obj = new PartnerRegistry_GetPartnerInfo_result({success: result});
        output.writeMessageBegin("GetPartnerInfo", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof ttypes.UnknownPartner) {
          result = new PartnerRegistry_GetPartnerInfo_result(err);
          output.writeMessageBegin("GetPartnerInfo", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("GetPartnerInfo", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.GetPartnerInfo(args.who, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof ttypes.UnknownPartner) {
          result_obj = new PartnerRegistry_GetPartnerInfo_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("GetPartnerInfo", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("GetPartnerInfo", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_AcknowledgePartnerIsAlive (seqid, input, output) {
    const args = new PartnerRegistry_AcknowledgePartnerIsAlive_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.AcknowledgePartnerIsAlive.length === 1) {
      new Promise((resolve) => resolve(this._handler.AcknowledgePartnerIsAlive.bind(this._handler)(
        args.myId
      ))).then(result => {
        const result_obj = new PartnerRegistry_AcknowledgePartnerIsAlive_result({success: result});
        output.writeMessageBegin("AcknowledgePartnerIsAlive", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof ttypes.UnknownPartner) {
          result = new PartnerRegistry_AcknowledgePartnerIsAlive_result(err);
          output.writeMessageBegin("AcknowledgePartnerIsAlive", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("AcknowledgePartnerIsAlive", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.AcknowledgePartnerIsAlive(args.myId, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof ttypes.UnknownPartner) {
          result_obj = new PartnerRegistry_AcknowledgePartnerIsAlive_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("AcknowledgePartnerIsAlive", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("AcknowledgePartnerIsAlive", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_IsPartnerAlive (seqid, input, output) {
    const args = new PartnerRegistry_IsPartnerAlive_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.IsPartnerAlive.length === 1) {
      new Promise((resolve) => resolve(this._handler.IsPartnerAlive.bind(this._handler)(
        args.who
      ))).then(result => {
        const result_obj = new PartnerRegistry_IsPartnerAlive_result({success: result});
        output.writeMessageBegin("IsPartnerAlive", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        if (err instanceof ttypes.UnknownPartner) {
          result = new PartnerRegistry_IsPartnerAlive_result(err);
          output.writeMessageBegin("IsPartnerAlive", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("IsPartnerAlive", Thrift.MessageType.EXCEPTION, seqid);
        }
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.IsPartnerAlive(args.who, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined') || err instanceof ttypes.UnknownPartner) {
          result_obj = new PartnerRegistry_IsPartnerAlive_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("IsPartnerAlive", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("IsPartnerAlive", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_SetPartnerInfo (seqid, input, output) {
    const args = new PartnerRegistry_SetPartnerInfo_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.SetPartnerInfo.length === 1) {
      new Promise((resolve) => resolve(this._handler.SetPartnerInfo.bind(this._handler)(
        args.information
      ))).then(result => {
        const result_obj = new PartnerRegistry_SetPartnerInfo_result({success: result});
        output.writeMessageBegin("SetPartnerInfo", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SetPartnerInfo", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.SetPartnerInfo(args.information, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new PartnerRegistry_SetPartnerInfo_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("SetPartnerInfo", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("SetPartnerInfo", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_SetAllPartners (seqid, input, output) {
    const args = new PartnerRegistry_SetAllPartners_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.SetAllPartners.length === 1) {
      new Promise((resolve) => resolve(this._handler.SetAllPartners.bind(this._handler)(
        args.allPartners
      ))).then(result => {
        const result_obj = new PartnerRegistry_SetAllPartners_result({success: result});
        output.writeMessageBegin("SetAllPartners", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SetAllPartners", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.SetAllPartners(args.allPartners, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new PartnerRegistry_SetAllPartners_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("SetAllPartners", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("SetAllPartners", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
};
export { PartnerRegistryProcessor as Processor };
