//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Int64 = require('node-int64');
import { v4 as uuid } from 'uuid';
type uuid = string;
import shared_ttypes = require('./shared_types.js');


import ttypes = require('./sim_types');
import SIM_SERVICE = ttypes.SIM_SERVICE

declare class Client {
    private output: thrift.TTransport;
    private pClass: thrift.TProtocol;
    private _seqid: number;

    constructor(output: thrift.TTransport, pClass: { new(trans: thrift.TTransport): thrift.TProtocol });

    getFrequency(): Promise<Int64>;

    getFrequency(callback?: (error: void, response: Int64)=>void): void;

    setFrequency(freq: Int64): Promise<void>;

    setFrequency(freq: Int64, callback?: (error: void, response: void)=>void): void;
  }

declare class Processor {
  private _handler: object;

  constructor(handler: object);
  process(input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_getFrequency(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
    process_setFrequency(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
}
