//
// Autogenerated by Thrift Compiler (0.24.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import { Thrift } from 'thrift';
import Int64 from 'node-int64';
import { v4 as uuid } from 'uuid';
import * as shared_ttypes from './shared_types.js';
import * as cspy_ttypes from './cspy_types.js';
import * as ServiceRegistry_ttypes from './ServiceRegistry_types.js';


import * as ttypes from './ampsync_types.js';
//HELPER FUNCTIONS AND STRUCTURES

const SoftCTI_SetSoftCTI_args = class {
  constructor(args) {
    this.on = null;
    if (args) {
      if (args.on !== undefined && args.on !== null) {
        this.on = args.on;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.BOOL) {
            this.on = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('SoftCTI_SetSoftCTI_args');
      if (this.on !== null && this.on !== undefined) {
        output.writeFieldBegin('on', Thrift.Type.BOOL, 1);
        output.writeBool(this.on);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const SoftCTI_SetSoftCTI_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('SoftCTI_SetSoftCTI_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const SoftCTI_GetSoftCTI_args = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('SoftCTI_GetSoftCTI_args');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const SoftCTI_GetSoftCTI_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.BOOL) {
            this.success = input.readBool();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('SoftCTI_GetSoftCTI_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
        output.writeBool(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const SoftCTI_CoreStarting_args = class {
  constructor(args) {
    this.core = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('SoftCTI_CoreStarting_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const SoftCTI_CoreStarting_result = class {
  constructor(args) {
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        input.skip(ftype);
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('SoftCTI_CoreStarting_result');
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const SoftCTI_CoreStopping_args = class {
  constructor(args) {
    this.core = null;
    if (args) {
      if (args.core !== undefined && args.core !== null) {
        this.core = args.core;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 1:
          if (ftype == Thrift.Type.I32) {
            this.core = input.readI32();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('SoftCTI_CoreStopping_args');
      if (this.core !== null && this.core !== undefined) {
        output.writeFieldBegin('core', Thrift.Type.I32, 1);
        output.writeI32(this.core);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const SoftCTI_CoreStopping_result = class {
  constructor(args) {
    this.success = null;
    if (args) {
      if (args.success !== undefined && args.success !== null) {
        this.success = args.success;
      }
    }
  }

  ["read"] (input) {
    input.incrementRecursionDepth();
    try {
      input.readStructBegin();
      while (true) {
        const ret = input.readFieldBegin();
        const ftype = ret.ftype;
        const fid = ret.fid;
        if (ftype == Thrift.Type.STOP) {
          break;
        }
        switch (fid) {
          case 0:
          if (ftype == Thrift.Type.I64) {
            this.success = input.readI64();
          } else {
            input.skip(ftype);
          }
          break;
          case 0:
            input.skip(ftype);
            break;
          default:
            input.skip(ftype);
        }
        input.readFieldEnd();
      }
      input.readStructEnd();
    } finally {
      input.decrementRecursionDepth();
    }
    return;
  }

  ["write"] (output) {
    output.incrementRecursionDepth();
    try {
      output.writeStructBegin('SoftCTI_CoreStopping_result');
      if (this.success !== null && this.success !== undefined) {
        output.writeFieldBegin('success', Thrift.Type.I64, 0);
        output.writeI64(this.success);
        output.writeFieldEnd();
      }
      output.writeFieldStop();
      output.writeStructEnd();
    } finally {
      output.decrementRecursionDepth();
    }
    return;
  }

};
const SoftCTIClient = class SoftCTIClient {
  constructor(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
  }
  seqid () { return this._seqid; }
  new_seqid () { return this._seqid += 1; }

  SetSoftCTI (on) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_SetSoftCTI(on);
    });
  }

  send_SetSoftCTI (on) {
    const output = new this.pClass(this.output);
    const params = {
      on: on
    };
    const args = new SoftCTI_SetSoftCTI_args(params);
    try {
      output.writeMessageBegin('SetSoftCTI', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_SetSoftCTI (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new SoftCTI_SetSoftCTI_result();
    result["read"](input);
    input.readMessageEnd();

    callback(null);
  }

  GetSoftCTI () {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_GetSoftCTI();
    });
  }

  send_GetSoftCTI () {
    const output = new this.pClass(this.output);
    const args = new SoftCTI_GetSoftCTI_args();
    try {
      output.writeMessageBegin('GetSoftCTI', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_GetSoftCTI (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new SoftCTI_GetSoftCTI_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('GetSoftCTI failed: unknown result');
  }

  CoreStarting (core) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_CoreStarting(core);
    });
  }

  send_CoreStarting (core) {
    const output = new this.pClass(this.output);
    const params = {
      core: core
    };
    const args = new SoftCTI_CoreStarting_args(params);
    try {
      output.writeMessageBegin('CoreStarting', Thrift.MessageType.ONEWAY, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      this.output.flush();
      const callback = this._reqs[this.seqid()] || function() {};
      delete this._reqs[this.seqid()];
      callback(null);
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  CoreStopping (core) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_CoreStopping(core);
    });
  }

  send_CoreStopping (core) {
    const output = new this.pClass(this.output);
    const params = {
      core: core
    };
    const args = new SoftCTI_CoreStopping_args(params);
    try {
      output.writeMessageBegin('CoreStopping', Thrift.MessageType.CALL, this.seqid());
      args["write"](output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_CoreStopping (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x["read"](input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new SoftCTI_CoreStopping_result();
    result["read"](input);
    input.readMessageEnd();

    if (null !== result.success) {
      return callback(null, result.success);
    }
    return callback('CoreStopping failed: unknown result');
  }
};
export { SoftCTIClient as Client };
const SoftCTIProcessor = class SoftCTIProcessor {
  constructor(handler) {
    this._handler = handler;
  }
  process (input, output) {
    const r = input.readMessageBegin();
    if (this['process_' + r.fname]) {
      return this['process_' + r.fname].call(this, r.rseqid, input, output);
    } else {
      input.skip(Thrift.Type.STRUCT);
      input.readMessageEnd();
      const x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
      output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
      x["write"](output);
      output.writeMessageEnd();
      output.flush();
    }
  }
  process_SetSoftCTI (seqid, input, output) {
    const args = new SoftCTI_SetSoftCTI_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.SetSoftCTI.length === 1) {
      new Promise((resolve) => resolve(this._handler.SetSoftCTI.bind(this._handler)(
        args.on
      ))).then(result => {
        const result_obj = new SoftCTI_SetSoftCTI_result({success: result});
        output.writeMessageBegin("SetSoftCTI", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SetSoftCTI", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.SetSoftCTI(args.on, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new SoftCTI_SetSoftCTI_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("SetSoftCTI", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("SetSoftCTI", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_GetSoftCTI (seqid, input, output) {
    const args = new SoftCTI_GetSoftCTI_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.GetSoftCTI.length === 0) {
      new Promise((resolve) => resolve(this._handler.GetSoftCTI.bind(this._handler)(
      ))).then(result => {
        const result_obj = new SoftCTI_GetSoftCTI_result({success: result});
        output.writeMessageBegin("GetSoftCTI", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetSoftCTI", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.GetSoftCTI((err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new SoftCTI_GetSoftCTI_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("GetSoftCTI", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("GetSoftCTI", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
  process_CoreStarting (seqid, input, output) {
    const args = new SoftCTI_CoreStarting_args();
    args["read"](input);
    input.readMessageEnd();
    this._handler.CoreStarting(args.core);
  }
  process_CoreStopping (seqid, input, output) {
    const args = new SoftCTI_CoreStopping_args();
    args["read"](input);
    input.readMessageEnd();
    if (this._handler.CoreStopping.length === 1) {
      new Promise((resolve) => resolve(this._handler.CoreStopping.bind(this._handler)(
        args.core
      ))).then(result => {
        const result_obj = new SoftCTI_CoreStopping_result({success: result});
        output.writeMessageBegin("CoreStopping", Thrift.MessageType.REPLY, seqid);
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("CoreStopping", Thrift.MessageType.EXCEPTION, seqid);
        result["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.CoreStopping(args.core, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new SoftCTI_CoreStopping_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("CoreStopping", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("CoreStopping", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj["write"](output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
};
export { SoftCTIProcessor as Processor };
